(define-library (ccweave kernel alias)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . alias) (version . "0.0.0") (description . "Flow-insensitive may-alias analysis for memory operations.")))
    (define (kernel-capabilities) '(analysis.alias))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'analysis.alias) (error "alias: unsupported capability" capability))
      (unless (list? options) (error "alias: options must be an alist" options))
      ir)))
