(define-library (ccweave kernel alias)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . alias) (version . "0.1.0") (description . "Publishes conservative may-alias facts for memory-effecting instructions.")))
    (define (kernel-capabilities) '(analysis.alias))
    (define (memory-op? op) (memq op '(load store call)))
    (define (kernel-apply cap ir options)
      (unless (eq? cap 'analysis.alias) (error "alias: unsupported capability" cap))
      (let f ((fi 0))
        (when (< fi (ir-function-count))
          (let b ((bi 0) (fn (ir-function-ref fi)))
            (when (< bi (function-block-count fn))
              (let i ((ii 0) (blk (function-block-ref fn bi)))
                (when (< ii (block-instr-count blk))
                  (let ((ins (block-instr-ref blk ii)))
                    (analysis-put! 'analysis.alias ins 'may-alias? (memory-op? (instr-opcode ins)))
                    (i (+ ii 1) blk))))
              (b (+ bi 1) fn)))
          (f (+ fi 1))))
      ir)))
