(define-library (ccweave kernel anf-normalize)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . anf-normalize) (version . "0.0.0") (description . "Normalizes expressions into administrative normal form.")))
    (define (kernel-capabilities) '(normalize.anf))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'normalize.anf) (error "anf-normalize: unsupported capability" capability))
      (unless (list? options) (error "anf-normalize: options must be an alist" options))
      ir)))
