(define-library (ccweave kernel block-merge)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . block-merge) (version . "0.1.0") (description . "Merges linear basic-block pairs.")))
    (define (kernel-capabilities) '(opt.block-merge))
    (define (kernel-apply cap ir options)
      (unless (eq? cap 'opt.block-merge) (error "block-merge: unsupported capability" cap))
      (unless (glue-has? 'block-merge!) (error "block-merge: Phase 4 accessors are unavailable"))
      (let f ((fi 0)) (when (< fi (ir-function-count))
        (let loop ((i 0) (fn (ir-function-ref fi)))
          (when (< i (function-block-count fn))
            (let ((block (function-block-ref fn i)))
              (when (= (block-succ-count block) 1)
                (let ((next (block-succ-ref block 0)))
                  (when (= (block-pred-count next) 1) (block-merge! block next))))
              (loop (+ i 1) fn))))
        (f (+ fi 1))))
      ir)))
