(define-library (ccweave kernel block-merge)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . block-merge) (version . "0.0.0") (description . "Merges compatible adjacent basic blocks.")))
    (define (kernel-capabilities) '(opt.block-merge))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.block-merge) (error "block-merge: unsupported capability" capability))
      (unless (list? options) (error "block-merge: options must be an alist" options))
      ir)))
