(define-library (ccweave kernel bounds-check-elim)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . bounds-check-elim) (version . "0.1.0") (description . "Eliminates statically satisfied bounds-check instructions.")))
    (define (kernel-capabilities) '(opt.bounds-check-elim))
    (define (kernel-apply cap ir options)
      (unless (eq? cap 'opt.bounds-check-elim) (error "bounds-check-elim: unsupported capability" cap))
      (let f ((fi 0)) (when (< fi (ir-function-count))
        (let b ((bi 0) (fn (ir-function-ref fi))) (when (< bi (function-block-count fn))
          (let loop ((ii (- (block-instr-count (function-block-ref fn bi)) 1)) (blk (function-block-ref fn bi)))
            (when (>= ii 0)
              (let ((ins (block-instr-ref blk ii)))
                (when (and (eq? (instr-opcode ins) 'bounds-check) (= (instr-operand-count ins) 2))
                  (let ((index (instr-operand ins 0)) (limit (instr-operand ins 1)))
                    (when (and (operand-const? index) (operand-const? limit)
                               (>= (const-int-value index) 0)
                               (< (const-int-value index) (const-int-value limit)))
                      (instr-delete! ins))))
              (loop (- ii 1) blk)))
          (b (+ bi 1) fn)))
        (f (+ fi 1))))
      ir))))
