(define-library (ccweave kernel bounds-check-elim)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . bounds-check-elim) (version . "0.0.0") (description . "Eliminates bounds checks proven redundant by range facts.")))
    (define (kernel-capabilities) '(opt.bounds-check-elim))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.bounds-check-elim) (error "bounds-check-elim: unsupported capability" capability))
      (unless (list? options) (error "bounds-check-elim: options must be an alist" options))
      ir)))
