(define-library (ccweave kernel callgraph)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . callgraph) (version . "0.1.0") (description . "Publishes direct call counts for each function.")))
    (define (kernel-capabilities) '(analysis.callgraph))
    (define (calls fn)
      (let b ((bi 0) (total 0))
        (if (>= bi (function-block-count fn)) total
            (let i ((ii 0) (sum total) (blk (function-block-ref fn bi)))
              (if (>= ii (block-instr-count blk)) (b (+ bi 1) sum)
                  (i (+ ii 1) (+ sum (if (eq? (instr-opcode (block-instr-ref blk ii)) 'call) 1 0)) blk))))))
    (define (kernel-apply cap ir options)
      (unless (eq? cap 'analysis.callgraph) (error "callgraph: unsupported capability" cap))
      (let loop ((i 0)) (when (< i (ir-function-count))
        (let ((fn (ir-function-ref i))) (analysis-put! 'analysis.callgraph fn 'direct-call-count (calls fn)))
        (loop (+ i 1))))
      ir)))
