(define-library (ccweave kernel callgraph)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . callgraph) (version . "0.0.0") (description . "Builds a conservative module call graph.")))
    (define (kernel-capabilities) '(analysis.callgraph))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'analysis.callgraph) (error "callgraph: unsupported capability" capability))
      (unless (list? options) (error "callgraph: options must be an alist" options))
      ir)))
