(define-library (ccweave kernel cfg-canonicalize)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . cfg-canonicalize)
        (version . "0.1.0")
        (description . "Collapses linear control-flow chains into canonical blocks.")))
    (define (kernel-capabilities) '(normalize.cfg))

    (define (canonicalize-function! function)
      (let loop ((index 0))
        (when (< index (function-block-count function))
          (let ((block (function-block-ref function index)))
            (if (= (block-succ-count block) 1)
                (let ((successor (block-succ-ref block 0)))
                  (if (and (not (eqv? block successor))
                           (= (block-pred-count successor) 1))
                      (begin
                        (block-merge! block successor)
                        (loop index))
                      (loop (+ index 1))))
                (loop (+ index 1)))))))

    (define (kernel-apply capability ir options)
      (unless (eq? capability 'normalize.cfg)
        (error "cfg-canonicalize: unsupported capability" capability))
      (unless (list? options)
        (error "cfg-canonicalize: options must be an alist" options))
      (unless (and (glue-has? 'block-succ-count)
                   (glue-has? 'block-succ-ref)
                   (glue-has? 'block-pred-count)
                   (glue-has? 'block-merge!))
        (error "cfg-canonicalize: CFG mutation accessors are unavailable"))
      (let loop ((index 0))
        (when (< index (ir-function-count))
          (canonicalize-function! (ir-function-ref index))
          (loop (+ index 1))))
      ir)))
