(define-library (ccweave kernel cfg-canonicalize)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . cfg-canonicalize) (version . "0.0.0") (description . "Canonicalizes control-flow graph structure.")))
    (define (kernel-capabilities) '(normalize.cfg))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'normalize.cfg) (error "cfg-canonicalize: unsupported capability" capability))
      (unless (list? options) (error "cfg-canonicalize: options must be an alist" options))
      ir)))
