;;; CCWeave Kernel: specialize closure calls with a statically known target.

(define-library (ccweave kernel closure-specialize)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . closure-specialize)
        (version . "1.0.0")
        (description . "Marks closure calls with a statically known function target.")))
    (define (kernel-capabilities) '(opt.functional-closure-specialization))
    (define (known-target? ins)
      (and (eq? (instr-opcode ins) 'closure.call)
           (> (instr-operand-count ins) 1)
           (eq? (operand-kind (instr-operand ins 1)) 'func)))
    (define (process-block! block)
      (let loop ((ii 0))
        (when (< ii (block-instr-count block))
          (let ((ins (block-instr-ref block ii)))
            (when (known-target? ins)
              (analysis-put! 'opt.functional-closure-specialization
                             ins 'specializable? #t)))
          (loop (+ ii 1)))))
    (define (process-function! fn)
      (let loop ((bi 0))
        (when (< bi (function-block-count fn))
          (process-block! (function-block-ref fn bi))
          (loop (+ bi 1)))))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.functional-closure-specialization)
        (error "closure-specialize: unsupported capability" capability))
      (unless (list? options)
        (error "closure-specialize: options must be an alist" options))
      (unless (and (glue-has? 'analysis-put!)
                   (glue-has? 'operand-kind))
        (error "closure-specialize: required accessors are unavailable"))
      (let loop ((fi 0))
        (when (< fi (ir-function-count))
          (process-function! (ir-function-ref fi))
          (loop (+ fi 1))))
      ir)))
