(define-library (ccweave kernel closure-convert)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . closure-convert) (version . "0.0.0") (description . "Converts closures into explicit environment records and calls.")))
    (define (kernel-capabilities) '(lower.closure-conversion))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'lower.closure-conversion) (error "closure-convert: unsupported capability" capability))
      (unless (list? options) (error "closure-convert: options must be an alist" options))
      ir)))
