(define-library (ccweave kernel closure-convert)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . closure-convert) (version . "0.1.0") (description . "Lowers closure construction and invocation to explicit runtime operations.")))
    (define (kernel-capabilities) '(lower.closure-conversion))
    (define (mapped op)
      (cond ((eq? op 'closure.make) 'runtime.closure.make)
            ((eq? op 'closure.call) 'runtime.closure.call)
            (else #f)))
    (define (operands ins)
      (let loop ((i 0) (xs '()))
        (if (>= i (instr-operand-count ins)) (reverse xs)
            (loop (+ i 1) (cons (instr-operand ins i) xs)))))
    (define (lower-block! block)
      (let loop ((i 0))
        (when (< i (block-instr-count block))
          (let* ((old (block-instr-ref block i)) (op (mapped (instr-opcode old))))
            (when op
              (let ((new (apply instr-build (cons op (operands old))))
                    (dest (instr-dest old)))
                (when (string? dest) (instr-set-dest! new dest))
                (instr-replace! old new)))
            (loop (+ i 1))))))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'lower.closure-conversion) (error "closure-convert: unsupported capability" capability))
      (unless (list? options) (error "closure-convert: options must be an alist" options))
      (unless (glue-has? 'instr-set-dest!) (error "closure-convert: scalar mutation accessors are unavailable"))
      (let f ((fi 0)) (when (< fi (ir-function-count))
        (let ((fn (ir-function-ref fi))) (let b ((bi 0))
          (when (< bi (function-block-count fn))
            (lower-block! (function-block-ref fn bi)) (b (+ bi 1)))))
        (f (+ fi 1))))
      ir)))
