;;; kernels/codegen-riscv64.scm
;;; CCWeave Kernel: RV64 instruction selection.
;;; Sources: .agents/ISA-Bundle/rv64.isa (§9 codegen).

(define-library (ccweave kernel codegen-riscv64)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . codegen-riscv64) (version . "0.3.0")
        (description . "Selects a scalar RV64 instruction subset covering arithmetic, compares, memory, and control flow.")))
    (define (kernel-capabilities) '(codegen.riscv64))

    (define op-table
      '((imov       . rv64.mv)
        (iadd       . rv64.add)
        (isub       . rv64.sub)
        (imul       . rv64.mul)
        (idiv       . rv64.div)
        (irem       . rv64.rem)
        (iand       . rv64.and)
        (ior        . rv64.or)
        (ixor       . rv64.xor)
        (shl        . rv64.sll)
        (lshr       . rv64.srl)
        (ashr       . rv64.sra)
        (ineg       . rv64.neg)
        (inot       . rv64.not)
        (icmp.eq    . rv64.seq)
        (icmp.ne    . rv64.sne)
        (icmp.lt    . rv64.slt)
        (icmp.le    . rv64.sle)
        (icmp.gt    . rv64.sgt)
        (icmp.ge    . rv64.sge)
        ;; FP arithmetic
        (fadd       . rv64.fadd.s)
        (fadd.d     . rv64.fadd.d)
        (fsub       . rv64.fsub.s)
        (fsub.d     . rv64.fsub.d)
        (fmul       . rv64.fmul.s)
        (fmul.d     . rv64.fmul.d)
        (fdiv       . rv64.fdiv.s)
        (fdiv.d     . rv64.fdiv.d)
        (fneg       . rv64.fneg)
        ;; FP compare
        (fcmp.eq    . rv64.feq)
        (fcmp.eq.d  . rv64.feq.d)
        (fcmp.lt    . rv64.flt)
        (fcmp.lt.d  . rv64.flt.d)
        (fcmp.le    . rv64.fle)
        (fcmp.le.d  . rv64.fle.d)
        ;; Width-specific loads
        (loadb      . rv64.lb)
        (loadh      . rv64.lh)
        (loadw      . rv64.lw)
        (load       . rv64.ld)
        (loadub     . rv64.lbu)
        (loaduh     . rv64.lhu)
        (loaduw     . rv64.lwu)
        ;; Width-specific stores
        (storeb     . rv64.sb)
        (storeh     . rv64.sh)
        (storew     . rv64.sw)
        (store      . rv64.sd)
        ;; Integer extension
        (extsb      . rv64.sext.b)
        (extub      . rv64.zext.b)
        (extsh      . rv64.sext.h)
        (extuh      . rv64.zext.h)
        (extsw      . rv64.sext.w)
        (extuw      . rv64.zext.w)
        ;; FP conversion
        (exts       . rv64.fcvt.d.s)
        (truncd     . rv64.fcvt.s.d)
        (stosi      . rv64.fcvt.w.s)
        (stosi.l    . rv64.fcvt.l.s)
        (stoui      . rv64.fcvt.wu.s)
        (stoui.l    . rv64.fcvt.lu.s)
        (dtosi      . rv64.fcvt.w.d)
        (dtosi.l    . rv64.fcvt.l.d)
        (dtoui      . rv64.fcvt.wu.d)
        (dtoui.l    . rv64.fcvt.lu.d)
        (swtof      . rv64.fcvt.s.w)
        (uwtof      . rv64.fcvt.s.wu)
        (sltof      . rv64.fcvt.d.l)
        (ultof      . rv64.fcvt.d.lu)
        (cast.fp.i  . rv64.fmv.x.w)
        (cast.i.fp  . rv64.fmv.w.x)
        ;; Misc
        (swap       . rv64.mv.swap)
        (udiv       . rv64.divu)
        (uidiv      . rv64.divu)
        (urem       . rv64.remu)
        (copy       . rv64.mv)
        ;; Compare flag extraction
        (reqz       . rv64.seqz)
        (rnez       . rv64.snez)
        (jmp        . rv64.j)
        (br         . rv64.beq)
        (ret        . rv64.ret)
        (call       . rv64.call)
        (syscall    . rv64.ecall)
        (call.dynamic . rv64.jalr)
        (call.virtual . rv64.jalr.virtual)
        (phi        . rv64.phi)))

    (define (mapped op)
      (let ((entry (assq op op-table)))
        (and entry (cdr entry))))

    (define (ops ins)
      (let loop ((i 0) (xs '())) (if (>= i (instr-operand-count ins)) (reverse xs)
        (loop (+ i 1) (cons (instr-operand ins i) xs)))))

    (define (select! b)
      (let loop ((i 0)) (when (< i (block-instr-count b))
        (let* ((old (block-instr-ref b i)) (op (mapped (instr-opcode old))))
          (when op (let ((new (apply instr-build (cons op (ops old)))) (d (instr-dest old)))
            (when (string? d) (instr-set-dest! new d)) (instr-replace! old new)))
          (loop (+ i 1))))))

    (define (kernel-apply capability ir options)
      (unless (eq? capability 'codegen.riscv64) (error "codegen-riscv64: unsupported capability" capability))
      (unless (list? options) (error "codegen-riscv64: options must be an alist" options))
      (unless (glue-has? 'instr-set-dest!) (error "codegen-riscv64: scalar mutation accessors are unavailable"))
      (let f ((fi 0)) (when (< fi (ir-function-count))
        (let ((fn (ir-function-ref fi))) (let b ((bi 0)) (when (< bi (function-block-count fn))
          (select! (function-block-ref fn bi)) (b (+ bi 1))))) (f (+ fi 1))))
      ir)))
