;;; kernels/codegen-riscv64.scm
;;; CCWeave Kernel: RV64 instruction selection.

(define-library (ccweave kernel codegen-riscv64)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . codegen-riscv64) (version . "0.2.0")
        (description . "Selects a scalar RV64 instruction subset covering arithmetic, compares, memory, and control flow.")))
    (define (kernel-capabilities) '(codegen.riscv64))

    (define op-table
      '((imov       . rv64.mv)
        (iadd       . rv64.add)
        (isub       . rv64.sub)
        (imul       . rv64.mul)
        (idiv       . rv64.div)
        (irem       . rv64.rem)
        (iand       . rv64.and)
        (ior        . rv64.or)
        (ixor       . rv64.xor)
        (shl        . rv64.sll)
        (lshr       . rv64.srl)
        (ashr       . rv64.sra)
        (ineg       . rv64.neg)
        (inot       . rv64.not)
        (icmp.eq    . rv64.seq)
        (icmp.ne    . rv64.sne)
        (icmp.lt    . rv64.slt)
        (icmp.le    . rv64.sle)
        (icmp.gt    . rv64.sgt)
        (icmp.ge    . rv64.sge)
        (load       . rv64.ld)
        (store      . rv64.sd)
        (jmp        . rv64.j)
        (br         . rv64.beq)
        (ret        . rv64.ret)
        (call       . rv64.call)
        (call.dynamic . rv64.jalr)
        (call.virtual . rv64.jalr.virtual)
        (phi        . rv64.phi)))

    (define (mapped op)
      (let ((entry (assq op op-table)))
        (and entry (cdr entry))))

    (define (ops ins)
      (let loop ((i 0) (xs '())) (if (>= i (instr-operand-count ins)) (reverse xs)
        (loop (+ i 1) (cons (instr-operand ins i) xs)))))

    (define (select! b)
      (let loop ((i 0)) (when (< i (block-instr-count b))
        (let* ((old (block-instr-ref b i)) (op (mapped (instr-opcode old))))
          (when op (let ((new (apply instr-build (cons op (ops old)))) (d (instr-dest old)))
            (when (string? d) (instr-set-dest! new d)) (instr-replace! old new)))
          (loop (+ i 1))))))

    (define (kernel-apply capability ir options)
      (unless (eq? capability 'codegen.riscv64) (error "codegen-riscv64: unsupported capability" capability))
      (unless (list? options) (error "codegen-riscv64: options must be an alist" options))
      (unless (glue-has? 'instr-set-dest!) (error "codegen-riscv64: scalar mutation accessors are unavailable"))
      (let f ((fi 0)) (when (< fi (ir-function-count))
        (let ((fn (ir-function-ref fi))) (let b ((bi 0)) (when (< bi (function-block-count fn))
          (select! (function-block-ref fn bi)) (b (+ bi 1))))) (f (+ fi 1))))
      ir)))
