;;; kernels/codegen-wasm32.scm
;;; CCWeave Kernel: WebAssembly (wasm32) instruction selection.

(define-library (ccweave kernel codegen-wasm32)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . codegen-wasm32) (version . "0.2.0")
        (description . "Selects a scalar WebAssembly instruction subset covering arithmetic, compares, memory, and control flow.")))
    (define (kernel-capabilities) '(codegen.wasm32))

    (define op-table
      '((imov       . wasm32.local.set)
        (iadd       . wasm32.add)
        (isub       . wasm32.sub)
        (imul       . wasm32.mul)
        (idiv       . wasm32.div_s)
        (irem       . wasm32.rem_s)
        (iand       . wasm32.and)
        (ior        . wasm32.or)
        (ixor       . wasm32.xor)
        (shl        . wasm32.shl)
        (lshr       . wasm32.shr_u)
        (ashr       . wasm32.shr_s)
        (ineg       . wasm32.neg)
        (inot       . wasm32.not)
        (icmp.eq    . wasm32.eq)
        (icmp.ne    . wasm32.ne)
        (icmp.lt    . wasm32.lt_s)
        (icmp.le    . wasm32.le_s)
        (icmp.gt    . wasm32.gt_s)
        (icmp.ge    . wasm32.ge_s)
        (load       . wasm32.load)
        (store      . wasm32.store)
        (jmp        . wasm32.br)
        (br         . wasm32.br_if)
        (ret        . wasm32.return)
        (call       . wasm32.call)
        (call.dynamic . wasm32.call_indirect)
        (call.virtual . wasm32.call_indirect.virtual)
        (phi        . wasm32.phi)))

    (define (mapped op)
      (let ((entry (assq op op-table)))
        (and entry (cdr entry))))

    (define (ops ins)
      (let loop ((i 0) (xs '())) (if (>= i (instr-operand-count ins)) (reverse xs)
        (loop (+ i 1) (cons (instr-operand ins i) xs)))))

    (define (select! b)
      (let loop ((i 0)) (when (< i (block-instr-count b))
        (let* ((old (block-instr-ref b i)) (op (mapped (instr-opcode old))))
          (when op (let ((new (apply instr-build (cons op (ops old)))) (d (instr-dest old)))
            (when (string? d) (instr-set-dest! new d)) (instr-replace! old new)))
          (loop (+ i 1))))))

    (define (kernel-apply capability ir options)
      (unless (eq? capability 'codegen.wasm32) (error "codegen-wasm32: unsupported capability" capability))
      (unless (list? options) (error "codegen-wasm32: options must be an alist" options))
      (unless (glue-has? 'instr-set-dest!) (error "codegen-wasm32: scalar mutation accessors are unavailable"))
      (let f ((fi 0)) (when (< fi (ir-function-count))
        (let ((fn (ir-function-ref fi))) (let b ((bi 0)) (when (< bi (function-block-count fn))
          (select! (function-block-ref fn bi)) (b (+ bi 1))))) (f (+ fi 1))))
      ir)))
