;;; kernels/codegen-aarch64.scm
;;; CCWeave Kernel: AArch64 instruction selection.

(define-library (ccweave kernel codegen-aarch64)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . codegen-aarch64) (version . "0.2.0")
        (description . "Selects a scalar AArch64 instruction subset covering arithmetic, compares, memory, and control flow.")))
    (define (kernel-capabilities) '(codegen.aarch64))

    (define op-table
      '((imov       . aarch64.mov)
        (iadd       . aarch64.add)
        (isub       . aarch64.sub)
        (imul       . aarch64.mul)
        (idiv       . aarch64.sdiv)
        (irem       . aarch64.msub)
        (iand       . aarch64.and)
        (ior        . aarch64.orr)
        (ixor       . aarch64.eor)
        (shl        . aarch64.lsl)
        (lshr       . aarch64.lsr)
        (ashr       . aarch64.asr)
        (ineg       . aarch64.neg)
        (inot       . aarch64.mvn)
        (icmp.eq    . aarch64.cmp.eq)
        (icmp.ne    . aarch64.cmp.ne)
        (icmp.lt    . aarch64.cmp.lt)
        (icmp.le    . aarch64.cmp.le)
        (icmp.gt    . aarch64.cmp.gt)
        (icmp.ge    . aarch64.cmp.ge)
        (load       . aarch64.ldr)
        (store      . aarch64.str)
        (jmp        . aarch64.b)
        (br         . aarch64.b.cond)
        (ret        . aarch64.ret)
        (call       . aarch64.bl)
        (call.dynamic . aarch64.blr)
        (call.virtual . aarch64.blr.virtual)
        (phi        . aarch64.phi)))

    (define (mapped op)
      (let ((entry (assq op op-table)))
        (and entry (cdr entry))))

    (define (ops ins)
      (let loop ((i 0) (xs '())) (if (>= i (instr-operand-count ins)) (reverse xs)
        (loop (+ i 1) (cons (instr-operand ins i) xs)))))

    (define (select! b)
      (let loop ((i 0)) (when (< i (block-instr-count b))
        (let* ((old (block-instr-ref b i)) (op (mapped (instr-opcode old))))
          (when op (let ((new (apply instr-build (cons op (ops old)))) (d (instr-dest old)))
            (when (string? d) (instr-set-dest! new d)) (instr-replace! old new)))
          (loop (+ i 1))))))

    (define (kernel-apply capability ir options)
      (unless (eq? capability 'codegen.aarch64) (error "codegen-aarch64: unsupported capability" capability))
      (unless (list? options) (error "codegen-aarch64: options must be an alist" options))
      (unless (glue-has? 'instr-set-dest!) (error "codegen-aarch64: scalar mutation accessors are unavailable"))
      (let f ((fi 0)) (when (< fi (ir-function-count))
        (let ((fn (ir-function-ref fi))) (let b ((bi 0)) (when (< bi (function-block-count fn))
          (select! (function-block-ref fn bi)) (b (+ bi 1))))) (f (+ fi 1))))
      ir)))
