(define-library (ccweave kernel codegen-wasm32)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . codegen-wasm32) (version . "0.0.0") (description . "Selects machine instructions for WebAssembly 32-bit targets.")))
    (define (kernel-capabilities) '(codegen.wasm32))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'codegen.wasm32) (error "codegen-wasm32: unsupported capability" capability))
      (unless (list? options) (error "codegen-wasm32: options must be an alist" options))
      ir)))
