(define-library (ccweave kernel codegen-x86-64)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . codegen-x86-64) (version . "0.0.0") (description . "Selects machine instructions for x86-64 targets.")))
    (define (kernel-capabilities) '(codegen.x86-64))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'codegen.x86-64) (error "codegen-x86-64: unsupported capability" capability))
      (unless (list? options) (error "codegen-x86-64: options must be an alist" options))
      ir)))
