(define-library (ccweave kernel codegen-wasm32)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . codegen-wasm32) (version . "0.1.0") (description . "Selects a scalar WebAssembly instruction subset.")))
    (define (kernel-capabilities) '(codegen.wasm32))
    (define (mapped op)
      (cond ((eq? op 'iadd) 'wasm32.add) ((eq? op 'isub) 'wasm32.sub)
            ((eq? op 'imul) 'wasm32.mul) ((eq? op 'load) 'wasm32.load)
            ((eq? op 'store) 'wasm32.store) (else #f)))
    (define (ops ins)
      (let loop ((i 0) (xs '())) (if (>= i (instr-operand-count ins)) (reverse xs)
        (loop (+ i 1) (cons (instr-operand ins i) xs)))))
    (define (select! b)
      (let loop ((i 0)) (when (< i (block-instr-count b))
        (let* ((old (block-instr-ref b i)) (op (mapped (instr-opcode old))))
          (when op (let ((new (apply instr-build (cons op (ops old)))) (d (instr-dest old)))
            (when (string? d) (instr-set-dest! new d)) (instr-replace! old new)))
          (loop (+ i 1))))))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'codegen.wasm32) (error "codegen-wasm32: unsupported capability" capability))
      (unless (list? options) (error "codegen-wasm32: options must be an alist" options))
      (unless (glue-has? 'instr-set-dest!) (error "codegen-wasm32: scalar mutation accessors are unavailable"))
      (let f ((fi 0)) (when (< fi (ir-function-count))
        (let ((fn (ir-function-ref fi))) (let b ((bi 0)) (when (< bi (function-block-count fn))
          (select! (function-block-ref fn bi)) (b (+ bi 1))))) (f (+ fi 1))))
      ir)))
