;;; kernels/code-sink.scm
;;; CCWeave Kernel: code sinking.

(define-library (ccweave kernel code-sink)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . code-sink) (version . "0.1.0")
        (description . "Publishes safe local sink positions for pure scalar computations.")))
    (define (kernel-capabilities) '(opt.sink))
    (define (pure? op) (memq op '(imov iadd isub imul iand ior ixor shl lshr ashr)))
    (define (last-use block start name)
      (let i ((ii start) (last #f))
        (if (>= ii (block-instr-count block)) last
            (let ((ins (block-instr-ref block ii)))
              (let o ((oi 0) (found last))
                (if (>= oi (instr-operand-count ins))
                    (i (+ ii 1) found)
                    (let ((operand (instr-operand ins oi)))
                      (o (+ oi 1)
                         (if (and (eq? (operand-kind operand) 'reg)
                                  (string=? (operand-name operand) name))
                             ii found)))))))))
    (define (analyze-block! block)
      (let loop ((i 0))
        (when (< i (block-instr-count block))
          (let* ((ins (block-instr-ref block i)) (dest (instr-dest ins)))
            (when (and (string? dest) (pure? (instr-opcode ins)))
              (let ((last (last-use block (+ i 1) dest)))
                (when (and last (> last (+ i 1)))
                  (analysis-put! 'opt.sink ins 'sink-before-index last))))
            (loop (+ i 1))))))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.sink)
        (error "code-sink: unsupported capability" capability))
      (unless (list? options)
        (error "code-sink: options must be an alist" options))
      (unless (and (glue-has? 'analysis-put!) (glue-has? 'instr-dest)
                   (glue-has? 'operand-kind) (glue-has? 'operand-name))
        (error "code-sink: analysis accessors are unavailable"))
      (let f ((fi 0)) (when (< fi (ir-function-count))
        (let ((fn (ir-function-ref fi))) (let b ((bi 0)) (when (< bi (function-block-count fn))
          (analyze-block! (function-block-ref fn bi)) (b (+ bi 1))))) (f (+ fi 1))))
      ir)))
