(define-library (ccweave kernel codegen-riscv64)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . codegen-riscv64) (version . "0.0.0") (description . "Selects machine instructions for RV64 targets.")))
    (define (kernel-capabilities) '(codegen.riscv64))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'codegen.riscv64) (error "codegen-riscv64: unsupported capability" capability))
      (unless (list? options) (error "codegen-riscv64: options must be an alist" options))
      ir)))
