;;; kernels/codegen-aarch64.scm
;;; CCWeave Kernel: AArch64 instruction selection.
;;; Sources: .agents/ISA-Bundle/arm64.isa (§9 codegen).

(define-library (ccweave kernel codegen-aarch64)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . codegen-aarch64) (version . "0.3.0")
        (description . "Selects a scalar AArch64 instruction subset covering arithmetic, compares, memory, and control flow.")))
    (define (kernel-capabilities) '(codegen.aarch64))

    (define op-table
      '((imov       . aarch64.mov)
        (iadd       . aarch64.add)
        (isub       . aarch64.sub)
        (imul       . aarch64.mul)
        (idiv       . aarch64.sdiv)
        (irem       . aarch64.msub)
        (iand       . aarch64.and)
        (ior        . aarch64.orr)
        (ixor       . aarch64.eor)
        (shl        . aarch64.lsl)
        (lshr       . aarch64.lsr)
        (ashr       . aarch64.asr)
        (ineg       . aarch64.neg)
        (inot       . aarch64.mvn)
        (icmp.eq    . aarch64.cmp.eq)
        (icmp.ne    . aarch64.cmp.ne)
        (icmp.lt    . aarch64.cmp.lt)
        (icmp.le    . aarch64.cmp.le)
        (icmp.gt    . aarch64.cmp.gt)
        (icmp.ge    . aarch64.cmp.ge)
        ;; FP arithmetic
        (fadd       . aarch64.fadd.s)
        (fadd.d     . aarch64.fadd.d)
        (fsub       . aarch64.fsub.s)
        (fsub.d     . aarch64.fsub.d)
        (fmul       . aarch64.fmul.s)
        (fmul.d     . aarch64.fmul.d)
        (fdiv       . aarch64.fdiv.s)
        (fdiv.d     . aarch64.fdiv.d)
        (fneg       . aarch64.fneg)
        ;; FP compare
        (fcmp.ord   . aarch64.fcmp.s)
        (fcmp.ord.d . aarch64.fcmp.d)
        ;; Width-specific loads
        (loadb      . aarch64.ldrb)
        (loadh      . aarch64.ldrh)
        (loadw      . aarch64.ldr.w)
        (load       . aarch64.ldr)
        (loadsb     . aarch64.ldrsb)
        (loadub     . aarch64.ldrb)
        (loadsh     . aarch64.ldrsh)
        (loaduh     . aarch64.ldrh)
        (loadsw     . aarch64.ldrsw)
        (loaduw     . aarch64.ldr.w)
        ;; Width-specific stores
        (storeb     . aarch64.strb)
        (storeh     . aarch64.strh)
        (storew     . aarch64.str.w)
        (store      . aarch64.str)
        (storel     . aarch64.str.x)
        (stores     . aarch64.str.s)
        (stored     . aarch64.str.d)
        ;; Integer extension
        (extsb      . aarch64.sxtb)
        (extub      . aarch64.uxtb)
        (extsh      . aarch64.sxth)
        (extuh      . aarch64.uxth)
        (extsw      . aarch64.sxtw)
        (extuw      . aarch64.mov.w)
        ;; FP conversion
        (exts       . aarch64.fcvt.d)
        (truncd     . aarch64.fcvt.s)
        (stosi      . aarch64.fcvtzs.w.s)
        (stoui      . aarch64.fcvtzu.w.s)
        (dtosi      . aarch64.fcvtzs.w.d)
        (dtoui      . aarch64.fcvtzu.w.d)
        (swtof      . aarch64.scvtf.s)
        (uwtof      . aarch64.ucvtf.s)
        (sltof      . aarch64.scvtf.d)
        (ultof      . aarch64.ucvtf.d)
        (cast.fp.i  . aarch64.fmov.to.gpr)
        (cast.i.fp  . aarch64.fmov.to.fpr)
        ;; Misc
        (swap       . aarch64.eor.swap)
        (udiv       . aarch64.udiv)
        (uidiv      . aarch64.udiv)
        (copy       . aarch64.mov)
        ;; Compare flag extraction
        (flagfeq    . aarch64.cset.eq)
        (flagfne    . aarch64.cset.ne)
        (flagflt    . aarch64.cset.lt)
        (flagfle    . aarch64.cset.le)
        (flagfgt    . aarch64.cset.gt)
        (flagfge    . aarch64.cset.ge)
        (flagflo    . aarch64.cset.lo)
        (flagfls    . aarch64.cset.ls)
        (flagfhi    . aarch64.cset.hi)
        (flagfhs    . aarch64.cset.hs)
        (jmp        . aarch64.b)
        (br         . aarch64.b.cond)
        (ret        . aarch64.ret)
        (call       . aarch64.bl)
        (syscall    . aarch64.svc)
        (call.dynamic . aarch64.blr)
        (call.virtual . aarch64.blr.virtual)
        (phi        . aarch64.phi)))

    (define (mapped op)
      (let ((entry (assq op op-table)))
        (and entry (cdr entry))))

    (define (ops ins)
      (let loop ((i 0) (xs '())) (if (>= i (instr-operand-count ins)) (reverse xs)
        (loop (+ i 1) (cons (instr-operand ins i) xs)))))

    (define (select! b)
      (let loop ((i 0)) (when (< i (block-instr-count b))
        (let* ((old (block-instr-ref b i)) (op (mapped (instr-opcode old))))
          (when op (let ((new (apply instr-build (cons op (ops old)))) (d (instr-dest old)))
            (when (string? d) (instr-set-dest! new d)) (instr-replace! old new)))
          (loop (+ i 1))))))

    (define (kernel-apply capability ir options)
      (unless (eq? capability 'codegen.aarch64) (error "codegen-aarch64: unsupported capability" capability))
      (unless (list? options) (error "codegen-aarch64: options must be an alist" options))
      (unless (glue-has? 'instr-set-dest!) (error "codegen-aarch64: scalar mutation accessors are unavailable"))
      (let f ((fi 0)) (when (< fi (ir-function-count))
        (let ((fn (ir-function-ref fi))) (let b ((bi 0)) (when (< bi (function-block-count fn))
          (select! (function-block-ref fn bi)) (b (+ bi 1))))) (f (+ fi 1))))
      ir)))
