;;; kernels/complex-lower.scm
;;; CCWeave Kernel: complex-number lowering.

(define-library (ccweave kernel complex-lower)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . complex-lower) (version . "0.1.0")
        (description . "Lowers complex arithmetic to explicit portable runtime libcalls.")))
    (define (kernel-capabilities) '(lower.complex))
    (define (mapped op)
      (cond ((eq? op 'complex.add) 'complex-libcall.add)
            ((eq? op 'complex.sub) 'complex-libcall.sub)
            ((eq? op 'complex.mul) 'complex-libcall.mul)
            ((eq? op 'complex.div) 'complex-libcall.div)
            (else #f)))
    (define (operands ins)
      (let loop ((i 0) (xs '()))
        (if (>= i (instr-operand-count ins)) (reverse xs)
            (loop (+ i 1) (cons (instr-operand ins i) xs)))))
    (define (lower-block! block)
      (let loop ((i 0))
        (when (< i (block-instr-count block))
          (let* ((old (block-instr-ref block i)) (op (mapped (instr-opcode old))))
            (when op
              (let ((new (apply instr-build (cons op (operands old))))
                    (dest (instr-dest old)))
                (when (string? dest) (instr-set-dest! new dest))
                (instr-replace! old new)))
            (loop (+ i 1))))))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'lower.complex)
        (error "complex-lower: unsupported capability" capability))
      (unless (list? options)
        (error "complex-lower: options must be an alist" options))
      (unless (glue-has? 'instr-set-dest!) (error "complex-lower: scalar mutation accessors are unavailable"))
      (let f ((fi 0)) (when (< fi (ir-function-count))
        (let ((fn (ir-function-ref fi))) (let b ((bi 0))
          (when (< bi (function-block-count fn))
            (lower-block! (function-block-ref fn bi)) (b (+ bi 1)))))
        (f (+ fi 1))))
      ir)))
