(define-library (ccweave kernel copy-prop)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . copy-prop) (version . "0.0.0") (description . "Propagates copies through compatible uses.")))
    (define (kernel-capabilities) '(opt.copy-propagation))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.copy-propagation) (error "copy-prop: unsupported capability" capability))
      (unless (list? options) (error "copy-prop: options must be an alist" options))
      ir)))
