(define-library (ccweave kernel copy-prop)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . copy-prop) (version . "0.1.0") (description . "Propagates register copies through later uses.")))
    (define (kernel-capabilities) '(opt.copy-propagation))

    (define (replace-uses-after! block start destination source)
      (let instructions ((instruction-index start) (instruction-count (block-instr-count block)))
        (when (< instruction-index instruction-count)
          (let ((instruction (block-instr-ref block instruction-index)))
            (let operands ((operand-index 0) (operand-count (instr-operand-count instruction)))
              (when (< operand-index operand-count)
                (let ((operand (instr-operand instruction operand-index)))
                  (when (and (eq? (operand-kind operand) 'reg)
                             (string=? (operand-name operand) destination))
                    (instr-set-operand! instruction operand-index
                                        (operand-reg-build source)))
                  (operands (+ operand-index 1) operand-count))))
            (instructions (+ instruction-index 1) instruction-count)))))

    (define (propagate-block! block)
      (let loop ((index 0) (count (block-instr-count block)))
        (when (< index count)
          (let* ((instruction (block-instr-ref block index))
                 (destination (instr-dest instruction)))
            (when (and destination
                       (eq? (instr-opcode instruction) 'imov)
                       (= (instr-operand-count instruction) 1))
              (let ((source (instr-operand instruction 0)))
                (when (eq? (operand-kind source) 'reg)
                  (replace-uses-after! block (+ index 1) destination
                                       (operand-name source)))))
            (loop (+ index 1) count)))))

    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.copy-propagation) (error "copy-prop: unsupported capability" capability))
      (unless (and (glue-has? 'instr-dest) (glue-has? 'instr-set-operand!)
                   (glue-has? 'operand-reg-build))
        (error "copy-prop: Phase 1 accessors are unavailable"))
      (let functions ((function-index 0) (function-count (ir-function-count)))
        (when (< function-index function-count)
          (let ((function (ir-function-ref function-index)))
            (let blocks ((block-index 0) (block-count (function-block-count function)))
              (when (< block-index block-count)
                (propagate-block! (function-block-ref function block-index))
                (blocks (+ block-index 1) block-count))))
          (functions (+ function-index 1) function-count)))
      ir)))
