(define-library (ccweave kernel cps-convert)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . cps-convert) (version . "0.0.0") (description . "Converts eligible functions into continuation-passing style.")))
    (define (kernel-capabilities) '(lower.cps-conversion))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'lower.cps-conversion) (error "cps-convert: unsupported capability" capability))
      (unless (list? options) (error "cps-convert: options must be an alist" options))
      ir)))
