(define-library (ccweave kernel cps-convert)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . cps-convert) (version . "0.1.0") (description . "Converts direct-return calls into explicit CPS tail calls.")))
    (define (kernel-capabilities) '(lower.cps-conversion))
    (define (operands ins)
      (let loop ((i 0) (xs '()))
        (if (>= i (instr-operand-count ins)) (reverse xs)
            (loop (+ i 1) (cons (instr-operand ins i) xs)))))
    (define (convert-block! block)
      (let ((n (block-instr-count block)))
        (when (>= n 2)
          (let ((call (block-instr-ref block (- n 2)))
                (ret (block-instr-ref block (- n 1))))
            (when (and (eq? (instr-opcode call) 'call)
                       (eq? (instr-opcode ret) 'ret)
                       (= (instr-operand-count ret) 1)
                       (string? (instr-dest call))
                       (eq? (operand-kind (instr-operand ret 0)) 'reg)
                       (string=? (instr-dest call)
                                 (operand-name (instr-operand ret 0))))
              (instr-replace! call
                (apply instr-build (cons 'cps.tail-call (operands call))))
              (instr-delete! ret))))))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'lower.cps-conversion) (error "cps-convert: unsupported capability" capability))
      (unless (list? options) (error "cps-convert: options must be an alist" options))
      (unless (and (glue-has? 'instr-dest) (glue-has? 'operand-kind)
                   (glue-has? 'operand-name))
        (error "cps-convert: scalar inspection accessors are unavailable"))
      (let f ((fi 0)) (when (< fi (ir-function-count))
        (let ((fn (ir-function-ref fi))) (let b ((bi 0))
          (when (< bi (function-block-count fn))
            (convert-block! (function-block-ref fn bi)) (b (+ bi 1)))))
        (f (+ fi 1))))
      ir)))
