(define-library (ccweave kernel cse)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . cse) (version . "0.1.0") (description . "Publishes local duplicate candidates for identical constant expressions.")))
    (define (kernel-capabilities) '(opt.cse))
    (define (kernel-apply cap ir options)
      (unless (eq? cap 'opt.cse) (error "cse: unsupported capability" cap))
      (let f ((fi 0)) (when (< fi (ir-function-count))
        (let b ((bi 0) (fn (ir-function-ref fi))) (when (< bi (function-block-count fn))
          (let i ((ii 0) (blk (function-block-ref fn bi))) (when (< ii (block-instr-count blk))
            (let ((ins (block-instr-ref blk ii)))
              (analysis-put! 'opt.cse ins 'constant-expression?
                             (and (= (instr-operand-count ins) 2)
                                  (operand-const? (instr-operand ins 0))
                                  (operand-const? (instr-operand ins 1)))))
            (i (+ ii 1) blk)))
          (b (+ bi 1) fn)))
        (f (+ fi 1))))
      ir)))
