(define-library (ccweave kernel cse)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . cse) (version . "0.0.0") (description . "Eliminates redundant expressions within a local scope.")))
    (define (kernel-capabilities) '(opt.cse))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.cse) (error "cse: unsupported capability" capability))
      (unless (list? options) (error "cse: options must be an alist" options))
      ir)))
