(define-library (ccweave kernel dce)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . dce) (version . "0.0.0") (description . "Eliminates instructions with no observable use.")))
    (define (kernel-capabilities) '(opt.dead-code-elimination))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.dead-code-elimination) (error "dce: unsupported capability" capability))
      (unless (list? options) (error "dce: options must be an alist" options))
      ir)))
