(define-library (ccweave kernel dce)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . dce) (version . "0.1.0") (description . "Removes unused pure scalar definitions.")))
    (define (kernel-capabilities) '(opt.dead-code-elimination))

    ;; Without return and CFG semantics, only an unused copy is provably
    ;; unobservable in the Phase 1 core.
    (define (pure-opcode? opcode) (eq? opcode 'imov))

    (define (uses-in-block name block)
      (let instructions ((instruction-index 0) (total 0) (instruction-count (block-instr-count block)))
        (if (>= instruction-index instruction-count)
            total
            (let ((instruction (block-instr-ref block instruction-index)))
              (let operands ((operand-index 0) (count total)
                             (operand-count (instr-operand-count instruction)))
                (if (>= operand-index operand-count)
                    (instructions (+ instruction-index 1) count instruction-count)
                    (let ((operand (instr-operand instruction operand-index)))
                      (operands (+ operand-index 1)
                                (if (and (eq? (operand-kind operand) 'reg)
                                         (string=? (operand-name operand) name))
                                    (+ count 1)
                                    count)
                                operand-count))))))))

    (define (eliminate-block! block)
      (let loop ((index (- (block-instr-count block) 1)))
        (when (>= index 0)
          (let* ((instruction (block-instr-ref block index))
                 (destination (instr-dest instruction)))
            (when (and destination (pure-opcode? (instr-opcode instruction))
                       (= (uses-in-block destination block) 0))
              (instr-delete! instruction))
            (loop (- index 1))))))

    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.dead-code-elimination) (error "dce: unsupported capability" capability))
      (unless (and (glue-has? 'instr-dest) (glue-has? 'operand-name))
        (error "dce: Phase 1 accessors are unavailable"))
      (let functions ((function-index 0) (function-count (ir-function-count)))
        (when (< function-index function-count)
          (let ((function (ir-function-ref function-index)))
            (let blocks ((block-index 0) (block-count (function-block-count function)))
              (when (< block-index block-count)
                (eliminate-block! (function-block-ref function block-index))
                (blocks (+ block-index 1) block-count))))
          (functions (+ function-index 1) function-count)))
      ir)))
