(define-library (ccweave kernel def-use)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . def-use) (version . "0.1.0") (description . "Publishes use counts for named instruction definitions.")))
    (define (kernel-capabilities) '(analysis.def-use))

    (define (uses-of name ir)
      (let functions ((function-index 0) (total 0) (function-count (ir-function-count)))
        (if (>= function-index function-count)
            total
            (let ((function (ir-function-ref function-index)))
              (let blocks ((block-index 0) (sum total) (block-count (function-block-count function)))
                (if (>= block-index block-count)
                    (functions (+ function-index 1) sum function-count)
                    (let ((block (function-block-ref function block-index)))
                      (let instructions ((instruction-index 0) (uses sum)
                                         (instruction-count (block-instr-count block)))
                        (if (>= instruction-index instruction-count)
                            (blocks (+ block-index 1) uses block-count)
                            (let ((instruction (block-instr-ref block instruction-index)))
                              (let operands ((operand-index 0) (count uses)
                                             (operand-count (instr-operand-count instruction)))
                                (if (>= operand-index operand-count)
                                    (instructions (+ instruction-index 1) count instruction-count)
                                    (let ((operand (instr-operand instruction operand-index)))
                                      (operands (+ operand-index 1)
                                                (if (and (eq? (operand-kind operand) 'reg)
                                                         (string=? (operand-name operand) name))
                                                    (+ count 1)
                                                    count)
                                                operand-count))))))))))))))

    (define (publish-block! block ir)
      (let loop ((index 0) (count (block-instr-count block)))
        (when (< index count)
          (let* ((instruction (block-instr-ref block index))
                 (destination (instr-dest instruction)))
            (when destination
              (analysis-put! 'analysis.def-use instruction 'use-count
                             (uses-of destination ir)))
            (loop (+ index 1) count)))))

    (define (kernel-apply capability ir options)
      (unless (eq? capability 'analysis.def-use) (error "def-use: unsupported capability" capability))
      (unless (and (glue-has? 'analysis-put!) (glue-has? 'instr-dest)
                   (glue-has? 'operand-name))
        (error "def-use: Phase 1 accessors are unavailable"))
      (let functions ((function-index 0) (function-count (ir-function-count)))
        (when (< function-index function-count)
          (let ((function (ir-function-ref function-index)))
            (let blocks ((block-index 0) (block-count (function-block-count function)))
              (when (< block-index block-count)
                (publish-block! (function-block-ref function block-index) ir)
                (blocks (+ block-index 1) block-count))))
          (functions (+ function-index 1) function-count)))
      ir)))
