(define-library (ccweave kernel def-use)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . def-use) (version . "0.0.0") (description . "Builds def-use relations for IR values.")))
    (define (kernel-capabilities) '(analysis.def-use))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'analysis.def-use) (error "def-use: unsupported capability" capability))
      (unless (list? options) (error "def-use: options must be an alist" options))
      ir)))
