(define-library (ccweave kernel deopt-points)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . deopt-points)
        (version . "0.1.0")
        (description . "Marks explicit On1x guard and deopt instructions as deoptimization points.")))
    (define (kernel-capabilities) '(vm.deopt-points))

    (define (deopt-opcode? opcode)
      (or (eq? opcode 'guard)
          (eq? opcode 'deopt)))

    (define (mark-block! block)
      (let loop ((index 0))
        (when (< index (block-instr-count block))
          (let ((instruction (block-instr-ref block index)))
            (when (deopt-opcode? (instr-opcode instruction))
              (analysis-put! 'vm.deopt-points instruction 'requires-state? #t)))
          (loop (+ index 1)))))

    (define (kernel-apply capability ir options)
      (unless (eq? capability 'vm.deopt-points)
        (error "deopt-points: unsupported capability" capability))
      (unless (list? options)
        (error "deopt-points: options must be an alist" options))
      (unless (eq? (ir-profile) 'on1x)
        (error "deopt-points: capability requires the on1x profile"))
      (unless (glue-has? 'analysis-put!)
        (error "deopt-points: analysis accessors are unavailable"))
      (let functions ((function-index 0))
        (when (< function-index (ir-function-count))
          (let ((function (ir-function-ref function-index)))
            (let blocks ((block-index 0))
              (when (< block-index (function-block-count function))
                (mark-block! (function-block-ref function block-index))
                (blocks (+ block-index 1)))))
          (functions (+ function-index 1))))
      ir)))
