(define-library (ccweave kernel deopt-points)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . deopt-points) (version . "0.0.0") (description . "Identifies program points requiring deoptimization state.")))
    (define (kernel-capabilities) '(vm.deopt-points))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'vm.deopt-points) (error "deopt-points: unsupported capability" capability))
      (unless (list? options) (error "deopt-points: options must be an alist" options))
      ir)))
