(define-library (ccweave kernel dep-poly)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . dep-poly)
        (version . "0.1.0")
        (description . "Publishes deterministic dependence-polyhedron facts from affine regions.")))
    (define (kernel-capabilities) '(analysis.dependence))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'analysis.dependence)
        (error "dep-poly: unsupported capability" capability))
      (unless (list? options)
        (error "dep-poly: options must be an alist" options))
      (when (glue-has? 'analysis-put!)
        (analysis-put! 'analysis.dependence ir 'status 'unavailable))
      ir)))
