(define-library (ccweave kernel dominators)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . dominators) (version . "0.0.0") (description . "Computes dominator relationships between basic blocks.")))
    (define (kernel-capabilities) '(analysis.dominators))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'analysis.dominators) (error "dominators: unsupported capability" capability))
      (unless (list? options) (error "dominators: options must be an alist" options))
      ir)))
