(define-library (ccweave kernel escape)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . escape) (version . "0.1.0") (description . "Publishes conservative function escape facts from call sites.")))
    (define (kernel-capabilities) '(analysis.escape))
    (define (kernel-apply cap ir options)
      (unless (eq? cap 'analysis.escape) (error "escape: unsupported capability" cap))
      (let f ((fi 0)) (when (< fi (ir-function-count))
        (let ((fn (ir-function-ref fi)) (escapes #f))
          (let b ((bi 0)) (when (< bi (function-block-count fn))
            (let i ((ii 0) (blk (function-block-ref fn bi))) (when (< ii (block-instr-count blk))
              (when (eq? (instr-opcode (block-instr-ref blk ii)) 'call) (set! escapes #t))
              (i (+ ii 1) blk)))
            (b (+ bi 1))))
          (analysis-put! 'analysis.escape fn 'may-escape? escapes))
        (f (+ fi 1))))
      ir)))
