(define-library (ccweave kernel escape-analysis)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . escape-analysis) (version . "0.1.0") (description . "Publishes conservative interprocedural escape summaries.")))
    (define (kernel-capabilities) '(analysis.escape))
    (define (kernel-apply cap ir options)
      (unless (eq? cap 'analysis.escape) (error "escape-analysis: unsupported capability" cap))
      (let loop ((i 0)) (when (< i (ir-function-count))
        (let ((fn (ir-function-ref i))) (analysis-put! 'analysis.escape fn 'summary 'unknown))
        (loop (+ i 1))))
      ir)))
