(define-library (ccweave kernel escape)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . escape) (version . "0.0.0") (description . "Classifies allocation escape behavior.")))
    (define (kernel-capabilities) '(analysis.escape))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'analysis.escape) (error "escape: unsupported capability" capability))
      (unless (list? options) (error "escape: options must be an alist" options))
      ir)))
