(define-library (ccweave kernel exception-lower)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . exception-lower) (version . "0.0.0") (description . "Lowers exception constructs to profile-specific control flow.")))
    (define (kernel-capabilities) '(lower.exceptions))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'lower.exceptions) (error "exception-lower: unsupported capability" capability))
      (unless (list? options) (error "exception-lower: options must be an alist" options))
      ir)))
