;;; CCWeave Kernel: identify eta-reducible functional wrappers.

(define-library (ccweave kernel functional-eta-reduce)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . functional-eta-reduce)
        (version . "1.0.0")
        (description . "Records functions whose body is a direct call-and-return wrapper.")))
    (define (kernel-capabilities) '(opt.functional-eta-reduction))
    (define (wrapper? block)
      (and (= (block-instr-count block) 2)
           (let ((call (block-instr-ref block 0))
                 (ret (block-instr-ref block 1)))
             (and (eq? (instr-opcode call) 'call)
                  (eq? (instr-opcode ret) 'ret)
                  (= (instr-operand-count ret) 1)
                  (string? (instr-dest call))
                  (eq? (operand-kind (instr-operand ret 0)) 'reg)
                  (string=? (instr-dest call)
                            (operand-name (instr-operand ret 0)))))))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.functional-eta-reduction)
        (error "functional-eta-reduce: unsupported capability" capability))
      (unless (list? options)
        (error "functional-eta-reduce: options must be an alist" options))
      (unless (and (glue-has? 'analysis-put!)
                   (glue-has? 'instr-dest)
                   (glue-has? 'operand-kind)
                   (glue-has? 'operand-name))
        (error "functional-eta-reduce: required accessors are unavailable"))
      (let f ((fi 0))
        (when (< fi (ir-function-count))
          (let ((fn (ir-function-ref fi)))
            (when (and (= (function-block-count fn) 1)
                       (wrapper? (function-block-ref fn 0)))
              (analysis-put! 'opt.functional-eta-reduction fn
                             'reducible? #t)))
          (f (+ fi 1))))
      ir)))
