;;; CCWeave Kernel: lower functional pipeline primitives to runtime calls.

(define-library (ccweave kernel functional-pipeline-lower)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . functional-pipeline-lower)
        (version . "1.0.0")
        (description . "Lowers compose and apply primitives to explicit runtime operations.")))
    (define (kernel-capabilities) '(lower.functional-pipeline))
    (define (mapped opcode)
      (cond ((eq? opcode 'compose) 'runtime.compose)
            ((eq? opcode 'apply) 'runtime.apply)
            (else #f)))
    (define (operands ins)
      (let loop ((i 0) (out '()))
        (if (>= i (instr-operand-count ins))
            (reverse out)
            (loop (+ i 1) (cons (instr-operand ins i) out)))))
    (define (rewrite-block! block)
      (let loop ((i 0))
        (when (< i (block-instr-count block))
          (let* ((old (block-instr-ref block i))
                 (new-op (mapped (instr-opcode old))))
            (when new-op
              (let ((new (apply instr-build (cons new-op (operands old)))))
                (when (string? (instr-dest old))
                  (instr-set-dest! new (instr-dest old)))
                (instr-replace! old new)))
            (loop (+ i 1))))))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'lower.functional-pipeline)
        (error "functional-pipeline-lower: unsupported capability" capability))
      (unless (list? options)
        (error "functional-pipeline-lower: options must be an alist" options))
      (unless (and (glue-has? 'instr-dest)
                   (glue-has? 'instr-set-dest!))
        (error "functional-pipeline-lower: destination accessors are unavailable"))
      (let f ((fi 0))
        (when (< fi (ir-function-count))
          (let ((fn (ir-function-ref fi)))
            (let b ((bi 0))
              (when (< bi (function-block-count fn))
                (rewrite-block! (function-block-ref fn bi))
                (b (+ bi 1)))))
          (f (+ fi 1))))
      ir)))
