(define-library (ccweave kernel gc-barrier-insert)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . gc-barrier-insert) (version . "0.0.0") (description . "Inserts garbage-collector write barriers.")))
    (define (kernel-capabilities) '(vm.gc-barrier-insertion))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'vm.gc-barrier-insertion) (error "gc-barrier-insert: unsupported capability" capability))
      (unless (list? options) (error "gc-barrier-insert: options must be an alist" options))
      ir)))
