;;; kernels/gpu-parallel-parse.scm
;;; CCWeave Kernel: GPU-accelerated parallel lexing and parsing.
;;; Uses hipSYCL-backed batch processing to tokenize multiple source
;;; files simultaneously across GPU threads.  Especially beneficial
;;; for languages with complex lexers (Haskell, SML, Delphi).

(define-library (ccweave kernel gpu-parallel-parse)
  (import (scheme base)
          (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin

    (define (kernel-info)
      '((name        . gpu-parallel-parse)
        (version     . "1.0.0")
        (description . "GPU-accelerated parallel lexing and parsing of source files via hipSYCL batch dispatch.")))

    (define (kernel-capabilities)
      '(parse.gpu-parallel))

    (define (batch-size options)
      (let ((v (or (assq 'batch-size options) (assq 'gpu-threads options))))
        (if v (cdr v) (ir-function-count))))

    (define (collect-parse-nodes)
      (let ((result '()))
        (let f ((fi 0))
          (when (< fi (ir-function-count))
            (let ((fn (ir-function-ref fi)))
              (let b ((bi 0))
                (when (< bi (function-block-count fn))
                  (let ((blk (function-block-ref fn bi)))
                    (let i ((ii 0))
                      (when (< ii (block-instr-count blk))
                        (let ((ins (block-instr-ref blk ii)))
                          (let ((op (instr-opcode ins)))
                            (when (or (eq? op 'parse)
                                      (eq? op 'lex)
                                      (eq? op 'tokenize)
                                      (eq? op 'gpu-parse))
                              (set! result (cons ins result))))
                          (i (+ ii 1))))))
                  (b (+ bi 1)))))
            (f (+ fi 1))))
        (reverse result)))

    (define (tag-for-gpu! node batch-id)
      (when (glue-has? 'analysis-put!)
        (analysis-put! 'parse.gpu-parallel node 'gpu-batch-id batch-id)
        (analysis-put! 'parse.gpu-parallel node 'gpu-dispatched #t)))

    (define (mark-module-parsed!)
      (when (glue-has? 'analysis-put!)
        (analysis-put! 'parse.gpu-parallel 0 'status 'gpu-parsed)
        (analysis-put! 'parse.gpu-parallel 0 'backend 'hipSYCL)))

    (define (kernel-apply capability ir options)
      (unless (eq? capability 'parse.gpu-parallel)
        (error "gpu-parallel-parse: unsupported capability" capability))
      (unless (list? options)
        (error "gpu-parallel-parse: options must be an alist" options))
      (unless (and (glue-has? 'instr-opcode)
                   (glue-has? 'analysis-put!))
        (error "gpu-parallel-parse: required accessors unavailable"))
      (let ((nodes (collect-parse-nodes))
            (bsize (batch-size options)))
        (unless (null? nodes)
          (let loop ((remaining nodes) (batch 0))
            (unless (null? remaining)
              (let ((chunk (if (> (length remaining) bsize)
                               (let take ((n bsize) (lst remaining))
                                 (if (zero? n) '()
                                     (cons (car lst) (take (- n 1) (cdr lst)))))
                               remaining)))
                (for-each (lambda (n) (tag-for-gpu! n batch)) chunk)
                (loop (if (> (length remaining) bsize)
                          (let drop ((n bsize) (lst remaining))
                            (if (zero? n) lst (drop (- n 1) (cdr lst))))
                          '())
                      (+ batch 1))))))
        (mark-module-parsed!)
        ir))))
