(define-library (ccweave kernel ic-install)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . ic-install) (version . "0.1.0") (description . "Assigns deterministic inline-cache slots to On1x dynamic calls.")))
    (define (kernel-capabilities) '(vm.inline-cache))
    (define (install-function! fn next)
      (let b ((bi 0) (slot next))
        (if (>= bi (function-block-count fn)) slot
            (let ((block (function-block-ref fn bi)))
              (let i ((ii 0) (current slot))
                (if (>= ii (block-instr-count block))
                    (b (+ bi 1) current)
                    (let ((ins (block-instr-ref block ii)))
                      (if (eq? (instr-opcode ins) 'call.dynamic)
                          (begin
                            (analysis-put! 'vm.inline-cache ins 'slot current)
                            (i (+ ii 1) (+ current 1)))
                          (i (+ ii 1) current)))))))))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'vm.inline-cache) (error "ic-install: unsupported capability" capability))
      (unless (list? options) (error "ic-install: options must be an alist" options))
      (unless (eq? (ir-profile) 'on1x) (error "ic-install: capability requires the on1x profile"))
      (unless (glue-has? 'analysis-put!) (error "ic-install: analysis accessors are unavailable"))
      (let f ((fi 0) (slot 0))
        (when (< fi (ir-function-count))
          (f (+ fi 1) (install-function! (ir-function-ref fi) slot))))
      ir)))
