(define-library (ccweave kernel ic-install)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . ic-install) (version . "0.0.0") (description . "Installs inline-cache operations for dynamic dispatch.")))
    (define (kernel-capabilities) '(vm.inline-cache))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'vm.inline-cache) (error "ic-install: unsupported capability" capability))
      (unless (list? options) (error "ic-install: options must be an alist" options))
      ir)))
