;;; CCWeave Kernel: forward an immediately preceding store into a load.

(define-library (ccweave kernel imperative-store-load-forward)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . imperative-store-load-forward)
        (version . "1.0.0")
        (description . "Forwards an adjacent store value into a matching load.")))
    (define (kernel-capabilities) '(opt.imperative-store-load-forwarding))
    (define (same-address? store load)
      (and (eq? (instr-opcode store) 'store)
           (eq? (instr-opcode load) 'load)
           (= (instr-operand-count store) 2)
           (= (instr-operand-count load) 1)
           (eqv? (instr-operand store 0) (instr-operand load 0))))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.imperative-store-load-forwarding)
        (error "imperative-store-load-forward: unsupported capability" capability))
      (unless (list? options)
        (error "imperative-store-load-forward: options must be an alist" options))
      (unless (and (glue-has? 'instr-dest) (glue-has? 'instr-set-dest!))
        (error "imperative-store-load-forward: destination accessors are unavailable"))
      (let f ((fi 0))
        (when (< fi (ir-function-count))
          (let ((fn (ir-function-ref fi)))
            (let b ((bi 0))
              (when (< bi (function-block-count fn))
                (let ((block (function-block-ref fn bi)))
                  (let i ((ii 1))
                    (when (< ii (block-instr-count block))
                      (let ((store (block-instr-ref block (- ii 1)))
                            (load (block-instr-ref block ii)))
                        (when (and (same-address? store load)
                                   (string? (instr-dest load)))
                          (let ((new (instr-build 'imov
                                                  (instr-operand store 1))))
                            (instr-set-dest! new (instr-dest load))
                            (instr-replace! load new))))
                      (i (+ ii 1)))))
                (b (+ bi 1)))))
          (f (+ fi 1))))
      ir)))
