;;; CCWeave Kernel: fold constant conditional branches.

(define-library (ccweave kernel imperative-branch-fold)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . imperative-branch-fold)
        (version . "1.0.0")
        (description . "Replaces branches with constant conditions by direct jumps.")))
    (define (kernel-capabilities) '(opt.imperative-branch-folding))
    (define (foldable? ins)
      (and (eq? (instr-opcode ins) 'br)
           (= (instr-operand-count ins) 3)
           (operand-const? (instr-operand ins 0))))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.imperative-branch-folding)
        (error "imperative-branch-fold: unsupported capability" capability))
      (unless (list? options)
        (error "imperative-branch-fold: options must be an alist" options))
      (let f ((fi 0))
        (when (< fi (ir-function-count))
          (let ((fn (ir-function-ref fi)))
            (let b ((bi 0))
              (when (< bi (function-block-count fn))
                (let ((block (function-block-ref fn bi)))
                  (let i ((ii 0))
                    (when (< ii (block-instr-count block))
                      (let ((ins (block-instr-ref block ii)))
                        (when (foldable? ins)
                          (let* ((condition (const-int-value (instr-operand ins 0)))
                                 (target (if (not (= condition 0))
                                             (instr-operand ins 1)
                                             (instr-operand ins 2)))
                                 (new (instr-build 'jmp target)))
                            (instr-replace! ins new))))
                      (i (+ ii 1)))))
                (b (+ bi 1)))))
          (f (+ fi 1))))
      ir)))
