(define-library (ccweave kernel inline-cost)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . inline-cost) (version . "0.1.0") (description . "Publishes instruction-count inlining costs per function.")))
    (define (kernel-capabilities) '(opt.inline-cost))
    (define (kernel-apply cap ir options)
      (unless (eq? cap 'opt.inline-cost) (error "inline-cost: unsupported capability" cap))
      (let f ((fi 0)) (when (< fi (ir-function-count))
        (let ((fn (ir-function-ref fi)))
          (let b ((bi 0) (cost 0))
            (if (>= bi (function-block-count fn))
                (analysis-put! 'opt.inline-cost fn 'instruction-cost cost)
                (b (+ bi 1) (+ cost (block-instr-count (function-block-ref fn bi)))))))
        (f (+ fi 1))))
      ir)))
