(define-library (ccweave kernel inline)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . inline) (version . "0.1.0") (description . "Inlines direct calls to constant-return leaf functions.")))
    (define (kernel-capabilities) '(opt.inline))
    (define (find-function name)
      (let loop ((i 0))
        (and (< i (ir-function-count))
             (let ((fn (ir-function-ref i)))
               (if (string=? (function-name fn) name)
                   fn
                   (loop (+ i 1)))))))
    (define (constant-return fn)
      (and fn
           (= (function-block-count fn) 1)
           (let ((block (function-block-ref fn 0)))
             (and (= (block-instr-count block) 1)
                  (let ((ret (block-instr-ref block 0)))
                    (and (eq? (instr-opcode ret) 'ret)
                         (= (instr-operand-count ret) 1)
                         (let ((value (instr-operand ret 0)))
                           (and (operand-const? value) value))))))))
    (define (inline-block! block)
      (let loop ((i 0))
        (when (< i (block-instr-count block))
          (let ((call (block-instr-ref block i)))
            (when (and (eq? (instr-opcode call) 'call)
                       (> (instr-operand-count call) 0)
                       (string? (instr-dest call))
                       (eq? (operand-kind (instr-operand call 0)) 'func))
              (let ((value
                      (constant-return
                        (find-function
                          (operand-name (instr-operand call 0))))))
                (when value
                  (let ((replacement (instr-build 'imov value)))
                    (instr-set-dest! replacement (instr-dest call))
                    (instr-replace! call replacement)))))
            (loop (+ i 1))))))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.inline) (error "inline: unsupported capability" capability))
      (unless (list? options) (error "inline: options must be an alist" options))
      (unless (and (glue-has? 'instr-dest) (glue-has? 'instr-set-dest!)
                   (glue-has? 'operand-kind) (glue-has? 'operand-name))
        (error "inline: scalar inspection accessors are unavailable"))
      (let f ((fi 0))
        (when (< fi (ir-function-count))
          (let ((fn (ir-function-ref fi)))
            (let b ((bi 0))
              (when (< bi (function-block-count fn))
                (inline-block! (function-block-ref fn bi))
                (b (+ bi 1)))))
          (f (+ fi 1))))
      ir)))
