(define-library (ccweave kernel inline)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . inline) (version . "0.0.0") (description . "Inlines eligible direct call sites.")))
    (define (kernel-capabilities) '(opt.inline))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.inline) (error "inline: unsupported capability" capability))
      (unless (list? options) (error "inline: options must be an alist" options))
      ir)))
