(define-library (ccweave kernel instr-canonicalize)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . instr-canonicalize) (version . "0.1.0") (description . "Moves constants to the right side of commutative scalar instructions.")))
    (define (kernel-capabilities) '(normalize.instructions))

    (define (commutative? opcode) (memq opcode '(iadd imul icmp.eq icmp.ne)))

    (define (canonicalize-block! block)
      (let loop ((index 0) (count (block-instr-count block)))
        (when (< index count)
          (let* ((instruction (block-instr-ref block index))
                 (opcode (instr-opcode instruction)))
            (when (and (commutative? opcode) (= (instr-operand-count instruction) 2))
              (let ((left (instr-operand instruction 0))
                    (right (instr-operand instruction 1))
                    (destination (instr-dest instruction)))
                (when (and (operand-const? left) (not (operand-const? right)))
                  (let ((replacement (instr-build opcode right left)))
                    (when destination (instr-set-dest! replacement destination))
                    (instr-replace! instruction replacement)))))
            (loop (+ index 1) count)))))

    (define (kernel-apply capability ir options)
      (unless (eq? capability 'normalize.instructions)
        (error "instr-canonicalize: unsupported capability" capability))
      (unless (glue-has? 'instr-set-dest!)
        (error "instr-canonicalize: Phase 1 accessors are unavailable"))
      (let functions ((function-index 0) (function-count (ir-function-count)))
        (when (< function-index function-count)
          (let ((function (ir-function-ref function-index)))
            (let blocks ((block-index 0) (block-count (function-block-count function)))
              (when (< block-index block-count)
                (canonicalize-block! (function-block-ref function block-index))
                (blocks (+ block-index 1) block-count))))
          (functions (+ function-index 1) function-count)))
      ir)))
