(define-library (ccweave kernel instr-canonicalize)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . instr-canonicalize) (version . "0.0.0") (description . "Canonicalizes equivalent instruction forms.")))
    (define (kernel-capabilities) '(normalize.instructions))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'normalize.instructions) (error "instr-canonicalize: unsupported capability" capability))
      (unless (list? options) (error "instr-canonicalize: options must be an alist" options))
      ir)))
