;;; CCWeave Kernel: Linux AArch64 low-level I/O wrappers.
;;; Sources: .agents/SYSCALL-AArch64.txt and .agents/DOING-SYSCALLS.md.

(define-library (ccweave kernel io-aarch64)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . io-aarch64)
        (version . "0.1.0")
        (description . "Lowers read, write, open, and close to Linux AArch64 syscalls.")))
    (define (kernel-capabilities) '(io.aarch64))

    ;; asm-generic: read=63, write=64, openat=56, close=57.
    (define (number opcode)
      (cond ((eq? opcode 'io.read) 63)
            ((eq? opcode 'io.write) 64)
            ((eq? opcode 'io.open) 56)
            ((eq? opcode 'io.close) 57)
            (else #f)))

    (define (ops ins)
      (let loop ((i 0) (out '()))
        (if (>= i (instr-operand-count ins))
            (reverse out)
            (loop (+ i 1) (cons (instr-operand ins i) out)))))

    (define (lower-block! block)
      (let loop ((i 0))
        (when (< i (block-instr-count block))
          (let* ((old (block-instr-ref block i))
                 (opcode (instr-opcode old))
                 (n (number opcode)))
            (when n
              (let* ((arguments (ops old))
                     ;; io.open is openat(AT_FDCWD, path, flags, mode).
                     (arguments (if (eq? opcode 'io.open)
                                    (cons (const-int-build -100) arguments)
                                    arguments))
                     (new (apply syscall-build (cons n arguments)))
                     (dest (instr-dest old)))
                (when (string? dest) (instr-set-dest! new dest))
                (instr-replace! old new))))
          (loop (+ i 1)))))

    (define (kernel-apply capability ir options)
      (unless (eq? capability 'io.aarch64)
        (error "io-aarch64: unsupported capability" capability))
      (unless (list? options)
        (error "io-aarch64: options must be an alist" options))
      (unless (and (glue-has? 'syscall-build)
                   (glue-has? 'const-int-build)
                   (glue-has? 'instr-set-dest!))
        (error "io-aarch64: required Glue accessors unavailable"))
      (let functions ((fi 0))
        (when (< fi (ir-function-count))
          (let ((fn (ir-function-ref fi)))
            (let blocks ((bi 0))
              (when (< bi (function-block-count fn))
                (lower-block! (function-block-ref fn bi))
                (blocks (+ bi 1)))))
          (functions (+ fi 1))))
      ir)))
