(define-library (ccweave kernel isel-tree-match)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . isel-tree-match)
        (version . "0.1.0")
        (description . "Publishes target-neutral instruction-selection pattern classes.")))
    (define (kernel-capabilities) '(codegen.isel-tree-match))

    (define (pattern-class opcode)
      (cond
        ((memq opcode '(iadd isub imul idiv irem iand ior ixor shl lshr ashr))
         'alu-binary)
        ((memq opcode '(ineg inot imov)) 'alu-unary)
        ((memq opcode '(icmp.eq icmp.ne icmp.lt icmp.le icmp.gt icmp.ge))
         'compare)
        ((eq? opcode 'load) 'memory-load)
        ((eq? opcode 'store) 'memory-store)
        ((eq? opcode 'call) 'call)
        (else #f)))

    (define (match-block! block)
      (let loop ((index 0))
        (when (< index (block-instr-count block))
          (let* ((instruction (block-instr-ref block index))
                 (class (pattern-class (instr-opcode instruction))))
            (when class
              (analysis-put! 'codegen.isel-tree-match instruction
                             'pattern-class class))
            (loop (+ index 1))))))

    (define (kernel-apply capability ir options)
      (unless (eq? capability 'codegen.isel-tree-match)
        (error "isel-tree-match: unsupported capability" capability))
      (unless (list? options)
        (error "isel-tree-match: options must be an alist" options))
      (unless (glue-has? 'analysis-put!)
        (error "isel-tree-match: analysis accessors are unavailable"))
      (let functions ((function-index 0))
        (when (< function-index (ir-function-count))
          (let ((function (ir-function-ref function-index)))
            (let blocks ((block-index 0))
              (when (< block-index (function-block-count function))
                (match-block! (function-block-ref function block-index))
                (blocks (+ block-index 1)))))
          (functions (+ function-index 1))))
      ir)))
