(define-library (ccweave kernel isel-tree-match)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . isel-tree-match) (version . "0.0.0") (description . "Matches expression trees to target instruction patterns.")))
    (define (kernel-capabilities) '(codegen.isel-tree-match))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'codegen.isel-tree-match) (error "isel-tree-match: unsupported capability" capability))
      (unless (list? options) (error "isel-tree-match: options must be an alist" options))
      ir)))
