(define-library (ccweave kernel isel-legalize)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . isel-legalize) (version . "0.0.0") (description . "Legalizes IR operations for instruction selection.")))
    (define (kernel-capabilities) '(codegen.isel-legalize))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'codegen.isel-legalize) (error "isel-legalize: unsupported capability" capability))
      (unless (list? options) (error "isel-legalize: options must be an alist" options))
      ir)))
