(define-library (ccweave kernel isel-legalize)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . isel-legalize)
        (version . "0.1.0")
        (description . "Legalizes scalar integer negation and complement.")))
    (define (kernel-capabilities) '(codegen.isel-legalize))

    (define (legalized instruction)
      (and (= (instr-operand-count instruction) 1)
           (let ((operand (instr-operand instruction 0)))
             (cond
               ((eq? (instr-opcode instruction) 'ineg)
                (instr-build 'isub (const-int-build 0) operand))
               ((eq? (instr-opcode instruction) 'inot)
                (instr-build 'ixor operand (const-int-build -1)))
               (else #f)))))

    (define (legalize-block! block)
      (let loop ((index 0))
        (when (< index (block-instr-count block))
          (let* ((instruction (block-instr-ref block index))
                 (replacement (legalized instruction)))
            (when replacement
              (let ((destination (instr-dest instruction)))
                (when (string? destination)
                  (instr-set-dest! replacement destination))
                (instr-replace! instruction replacement)))
            (loop (+ index 1))))))

    (define (kernel-apply capability ir options)
      (unless (eq? capability 'codegen.isel-legalize)
        (error "isel-legalize: unsupported capability" capability))
      (unless (list? options)
        (error "isel-legalize: options must be an alist" options))
      (unless (and (glue-has? 'instr-dest)
                   (glue-has? 'instr-set-dest!))
        (error "isel-legalize: scalar mutation accessors are unavailable"))
      (let functions ((function-index 0))
        (when (< function-index (ir-function-count))
          (let ((function (ir-function-ref function-index)))
            (let blocks ((block-index 0))
              (when (< block-index (function-block-count function))
                (legalize-block! (function-block-ref function block-index))
                (blocks (+ block-index 1)))))
          (functions (+ function-index 1))))
      ir)))
