(define-library (ccweave kernel isl-schedule)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . isl-schedule)
        (version . "0.1.0")
        (description . "Publishes pinned ISL schedule-tree metadata for affine regions.")))
    (define (kernel-capabilities) '(opt.schedule))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.schedule)
        (error "isl-schedule: unsupported capability" capability))
      (unless (list? options)
        (error "isl-schedule: options must be an alist" options))
      (when (glue-has? 'analysis-put!)
        (analysis-put! 'opt.schedule ir 'status 'unavailable))
      ir)))
