(define-library (ccweave kernel jump-thread)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . jump-thread) (version . "0.0.0") (description . "Threads control flow through determinable branches.")))
    (define (kernel-capabilities) '(opt.jump-threading))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.jump-threading) (error "jump-thread: unsupported capability" capability))
      (unless (list? options) (error "jump-thread: options must be an alist" options))
      ir)))
