;;; kernels/jump-threading.scm
;;; CCWeave Kernel: control-flow jump threading.

(define-library (ccweave kernel jump-threading)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . jump-threading) (version . "0.1.0")
        (description . "Publishes deterministic two-edge jump-threading opportunities.")))
    (define (kernel-capabilities) '(opt.jump-threading))
    (define (analyze-function! fn)
      (let loop ((i 0))
        (when (< i (function-block-count fn))
          (let ((block (function-block-ref fn i)))
            (when (= (block-succ-count block) 1)
              (let ((middle (block-succ-ref block 0)))
                (when (and (= (block-pred-count middle) 1)
                           (= (block-succ-count middle) 1))
                  (let ((target (block-succ-ref middle 0)))
                    (when (not (eqv? target block))
                      (analysis-put! 'opt.jump-threading block
                                     'exclusive-thread-target target))))))
            (loop (+ i 1))))))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.jump-threading)
        (error "jump-threading: unsupported capability" capability))
      (unless (list? options)
        (error "jump-threading: options must be an alist" options))
      (unless (and (glue-has? 'analysis-put!) (glue-has? 'block-succ-count)
                   (glue-has? 'block-succ-ref) (glue-has? 'block-pred-count))
        (error "jump-threading: CFG analysis accessors are unavailable"))
      (let f ((fi 0)) (when (< fi (ir-function-count))
        (analyze-function! (ir-function-ref fi)) (f (+ fi 1))))
      ir)))
