(define-library (ccweave kernel jump-thread)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . jump-thread) (version . "0.1.0") (description . "Publishes one-hop jump-threading targets.")))
    (define (kernel-capabilities) '(opt.jump-threading))
    (define (analyze-function! fn)
      (let loop ((i 0))
        (when (< i (function-block-count fn))
          (let ((block (function-block-ref fn i)))
            (when (= (block-succ-count block) 1)
              (let ((middle (block-succ-ref block 0)))
                (when (and (not (eqv? middle block))
                           (= (block-succ-count middle) 1))
                  (let ((target (block-succ-ref middle 0)))
                    (when (and (not (eqv? target middle))
                               (not (eqv? target block)))
                      (analysis-put! 'opt.jump-threading block
                                     'thread-target target))))))
            (loop (+ i 1))))))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.jump-threading) (error "jump-thread: unsupported capability" capability))
      (unless (list? options) (error "jump-thread: options must be an alist" options))
      (unless (and (glue-has? 'analysis-put!) (glue-has? 'block-succ-count)
                   (glue-has? 'block-succ-ref))
        (error "jump-thread: CFG analysis accessors are unavailable"))
      (let f ((fi 0)) (when (< fi (ir-function-count))
        (analyze-function! (ir-function-ref fi)) (f (+ fi 1))))
      ir)))
