(define-library (ccweave kernel lambda-lift)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . lambda-lift) (version . "0.0.0") (description . "Lifts nested functions into top-level functions.")))
    (define (kernel-capabilities) '(lower.lambda-lifting))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'lower.lambda-lifting) (error "lambda-lift: unsupported capability" capability))
      (unless (list? options) (error "lambda-lift: options must be an alist" options))
      ir)))
