(define-library (ccweave kernel licm)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . licm) (version . "0.0.0") (description . "Hoists loop-invariant computations.")))
    (define (kernel-capabilities) '(opt.licm))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.licm) (error "licm: unsupported capability" capability))
      (unless (list? options) (error "licm: options must be an alist" options))
      ir)))
