(define-library (ccweave kernel licm)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . licm) (version . "0.1.0") (description . "Publishes constant-only loop-invariant candidates.")))
    (define (kernel-capabilities) '(opt.licm))
    (define (kernel-apply cap ir options)
      (unless (eq? cap 'opt.licm) (error "licm: unsupported capability" cap))
      (let f ((fi 0)) (when (< fi (ir-function-count))
        (let b ((bi 0) (fn (ir-function-ref fi))) (when (< bi (function-block-count fn))
          (let i ((ii 0) (blk (function-block-ref fn bi))) (when (< ii (block-instr-count blk))
            (let ((ins (block-instr-ref blk ii)))
              (analysis-put! 'opt.licm ins 'constant-invariant?
                (let o ((oi 0)) (or (= oi (instr-operand-count ins))
                  (and (operand-const? (instr-operand ins oi)) (o (+ oi 1)))))))
            (i (+ ii 1) blk)))
          (b (+ bi 1) fn)))
        (f (+ fi 1))))
      ir)))
