(define-library (ccweave kernel liveness)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . liveness) (version . "0.1.0") (description . "Publishes same-block liveness for named definitions.")))
    (define (kernel-capabilities) '(analysis.liveness))
    (define (used-after? name block start)
      (let i ((ii start)) (if (>= ii (block-instr-count block)) #f
        (let o ((oi 0) (ins (block-instr-ref block ii)))
          (if (>= oi (instr-operand-count ins)) (i (+ ii 1))
            (let ((op (instr-operand ins oi)))
              (if (and (eq? (operand-kind op) 'reg) (string=? (operand-name op) name)) #t
                (o (+ oi 1) ins))))))))
    (define (kernel-apply cap ir options)
      (unless (eq? cap 'analysis.liveness) (error "liveness: unsupported capability" cap))
      (let f ((fi 0)) (when (< fi (ir-function-count))
        (let b ((bi 0) (fn (ir-function-ref fi))) (when (< bi (function-block-count fn))
          (let i ((ii 0) (blk (function-block-ref fn bi))) (when (< ii (block-instr-count blk))
            (let ((ins (block-instr-ref blk ii)) (dest (instr-dest (block-instr-ref blk ii))))
              (when dest (analysis-put! 'analysis.liveness ins 'live-out? (used-after? dest blk (+ ii 1)))))
            (i (+ ii 1) blk)))
          (b (+ bi 1) fn)))
        (f (+ fi 1))))
      ir)))
