(define-library (ccweave kernel liveness)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . liveness) (version . "0.0.0") (description . "Computes value liveness across control flow.")))
    (define (kernel-capabilities) '(analysis.liveness))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'analysis.liveness) (error "liveness: unsupported capability" capability))
      (unless (list? options) (error "liveness: options must be an alist" options))
      ir)))
