(define-library (ccweave kernel load-store-forward)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . load-store-forward) (version . "0.1.0") (description . "Publishes adjacent store-to-load forwarding candidates.")))
    (define (kernel-capabilities) '(opt.load-store-forward))
    (define (kernel-apply cap ir options)
      (unless (eq? cap 'opt.load-store-forward) (error "load-store-forward: unsupported capability" cap))
      (let f ((fi 0)) (when (< fi (ir-function-count))
        (let b ((bi 0) (fn (ir-function-ref fi))) (when (< bi (function-block-count fn))
          (let i ((ii 1) (blk (function-block-ref fn bi))) (when (< ii (block-instr-count blk))
            (let ((prior (block-instr-ref blk (- ii 1))) (ins (block-instr-ref blk ii)))
              (analysis-put! 'opt.load-store-forward ins 'adjacent-store?
                             (and (eq? (instr-opcode prior) 'store) (eq? (instr-opcode ins) 'load))))
            (i (+ ii 1) blk)))
          (b (+ bi 1) fn)))
        (f (+ fi 1))))
      ir)))
