(define-library (ccweave kernel load-store-forward)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . load-store-forward) (version . "0.0.0") (description . "Forwards stored values to compatible loads.")))
    (define (kernel-capabilities) '(opt.load-store-forward))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.load-store-forward) (error "load-store-forward: unsupported capability" capability))
      (unless (list? options) (error "load-store-forward: options must be an alist" options))
      ir)))
