(define-library (ccweave kernel loop-detect)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . loop-detect) (version . "0.1.0") (description . "Publishes loop back-edge facts for CFG block targets.")))
    (define (kernel-capabilities) '(analysis.loops))
    (define (kernel-apply cap ir options)
      (unless (eq? cap 'analysis.loops) (error "loop-detect: unsupported capability" cap))
      (let f ((fi 0)) (when (< fi (ir-function-count))
        (let ((fn (ir-function-ref fi)))
          (let b ((bi 0)) (when (< bi (function-block-count fn))
            (let ((blk (function-block-ref fn bi)) (back #f))
              (let s ((si 0)) (when (< si (block-succ-count blk))
                (let scan ((j 0)) (when (< j bi)
                  (when (= (block-succ-ref blk si) (function-block-ref fn j)) (set! back #t))
                  (scan (+ j 1))))
                (s (+ si 1))))
              (analysis-put! 'analysis.loops blk 'backedge? back))
            (b (+ bi 1)))))
        (f (+ fi 1))))
      ir)))
