(define-library (ccweave kernel loop-detect)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . loop-detect) (version . "0.0.0") (description . "Identifies natural loops in the control-flow graph.")))
    (define (kernel-capabilities) '(analysis.loops))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'analysis.loops) (error "loop-detect: unsupported capability" capability))
      (unless (list? options) (error "loop-detect: options must be an alist" options))
      ir)))
