(define-library (ccweave kernel loop-vectorize)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . loop-vectorize) (version . "0.1.0")
        (description . "Applies conservative width-explicit vector operations to legal loops.")))
    (define (kernel-capabilities) '(opt.loop-vectorize))
    (define (vop op) (cond ((eq? op 'fadd) 'vadd.f32x4)
                            ((eq? op 'fsub) 'vsub.f32x4)
                            ((eq? op 'fmul) 'vmul.f32x4)
                            ((eq? op 'iadd) 'vadd.i32x4)
                            ((eq? op 'isub) 'vsub.i32x4)
                            ((eq? op 'imul) 'vmul.i32x4)
                            (else #f)))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.loop-vectorize)
        (error "loop-vectorize: unsupported capability" capability))
      (unless (list? options) (error "loop-vectorize: options must be an alist" options))
      (unless (and (glue-has? 'analysis-put!) (glue-has? 'instr-build)
                   (glue-has? 'instr-replace!) (glue-has? 'instr-opcode))
        (error "loop-vectorize: required accessors unavailable"))
      (let f ((fi 0))
        (when (< fi (ir-function-count))
          (let ((fn (ir-function-ref fi)))
            (let b ((bi 0))
              (when (< bi (function-block-count fn))
                (let ((blk (function-block-ref fn bi)))
                  (when (and (glue-has? 'block-succ-count)
                             (glue-has? 'block-succ-ref)
                             (= (block-succ-count blk) 1)
                             (eqv? (block-succ-ref blk 0) blk))
                    (analysis-put! 'opt.loop-vectorize blk 'vf 4)
                    (analysis-put! 'opt.loop-vectorize blk 'epilogue 'scalar-tail)
                    (let i ((ii 0))
                      (when (< ii (block-instr-count blk))
                        (let* ((old (block-instr-ref blk ii)) (op (vop (instr-opcode old))))
                          (when op
                            (let ((new (apply instr-build (cons op (let ops ((j 0) (r '()))
                                                                    (if (>= j (instr-operand-count old)) (reverse r)
                                                                        (ops (+ j 1) (cons (instr-operand old j) r))))))))
                              (when (and (glue-has? 'instr-dest) (instr-dest old))
                                (instr-set-dest! new (instr-dest old)))
                              (instr-replace! old new)))
                          (i (+ ii 1)))))))
                (b (+ bi 1)))))
          (f (+ fi 1))))
      ir)))
