;;; kernels/loop-fusion.scm
;;; CCWeave Kernel: loop fusion.

(define-library (ccweave kernel loop-fusion)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . loop-fusion) (version . "0.1.0")
        (description . "Publishes adjacent self-loop fusion candidates.")))
    (define (kernel-capabilities) '(opt.loop-fusion))
    (define (self-loop? block)
      (and (= (block-succ-count block) 1)
           (eqv? (block-succ-ref block 0) block)))
    (define (analyze-function! fn)
      (let loop ((i 0))
        (when (< (+ i 1) (function-block-count fn))
          (let ((first (function-block-ref fn i))
                (second (function-block-ref fn (+ i 1))))
            (when (and (self-loop? first) (self-loop? second))
              (analysis-put! 'opt.loop-fusion first 'candidate-next second))
            (loop (+ i 1))))))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.loop-fusion)
        (error "loop-fusion: unsupported capability" capability))
      (unless (list? options)
        (error "loop-fusion: options must be an alist" options))
      (unless (and (glue-has? 'analysis-put!) (glue-has? 'block-succ-count)
                   (glue-has? 'block-succ-ref))
        (error "loop-fusion: CFG analysis accessors are unavailable"))
      (let f ((fi 0)) (when (< fi (ir-function-count))
        (analyze-function! (ir-function-ref fi)) (f (+ fi 1))))
      ir)))
