;;; kernels/loop-unroll.scm
;;; CCWeave Kernel: loop unrolling.

(define-library (ccweave kernel loop-unroll)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . loop-unroll) (version . "0.1.0")
        (description . "Publishes conservative factor-two candidates for self-loop blocks.")))
    (define (kernel-capabilities) '(opt.loop-unroll))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.loop-unroll)
        (error "loop-unroll: unsupported capability" capability))
      (unless (list? options)
        (error "loop-unroll: options must be an alist" options))
      (unless (and (glue-has? 'analysis-put!) (glue-has? 'block-succ-count)
                   (glue-has? 'block-succ-ref))
        (error "loop-unroll: CFG analysis accessors are unavailable"))
      (let f ((fi 0))
        (when (< fi (ir-function-count))
          (let ((fn (ir-function-ref fi)))
            (let b ((bi 0))
              (when (< bi (function-block-count fn))
                (let ((block (function-block-ref fn bi)))
                  (when (and (= (block-succ-count block) 1)
                             (eqv? (block-succ-ref block 0) block))
                    (analysis-put! 'opt.loop-unroll block 'factor 2)))
                (b (+ bi 1)))))
          (f (+ fi 1))))
      ir)))
