;;; kernels/mem2reg.scm
;;; CCWeave Kernel: stack-slot promotion to SSA.

(define-library (ccweave kernel mem2reg)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . mem2reg) (version . "0.1.0")
        (description . "Promotes exact local stack-slot store/load triples to SSA copies.")))
    (define (kernel-capabilities) '(opt.mem2reg))
    (define (slot-reference? operand name)
      (and (eq? (operand-kind operand) 'reg)
           (string=? (operand-name operand) name)))
    (define (promote-block! block)
      (let loop ((i 0))
        (when (< i (block-instr-count block))
          (if (< (+ i 2) (block-instr-count block))
              (let* ((slot (block-instr-ref block i))
                     (store (block-instr-ref block (+ i 1)))
                     (load (block-instr-ref block (+ i 2)))
                     (name (instr-dest slot)))
                (if (and (eq? (instr-opcode slot) 'stack-slot)
                         (string? name)
                         (eq? (instr-opcode store) 'store)
                         (= (instr-operand-count store) 2)
                         (slot-reference? (instr-operand store 0) name)
                         (eq? (instr-opcode load) 'load)
                         (= (instr-operand-count load) 1)
                         (slot-reference? (instr-operand load 0) name)
                         (string? (instr-dest load)))
                    (let ((replacement
                            (instr-build 'imov (instr-operand store 1))))
                      (instr-set-dest! replacement (instr-dest load))
                      (instr-replace! load replacement)
                      (instr-delete! store)
                      (instr-delete! slot)
                      (loop i))
                    (loop (+ i 1))))
              (loop (+ i 1))))))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.mem2reg)
        (error "mem2reg: unsupported capability" capability))
      (unless (list? options)
        (error "mem2reg: options must be an alist" options))
      (unless (and (glue-has? 'instr-dest) (glue-has? 'instr-set-dest!)
                   (glue-has? 'operand-kind) (glue-has? 'operand-name))
        (error "mem2reg: scalar mutation accessors are unavailable"))
      (let f ((fi 0))
        (when (< fi (ir-function-count))
          (let ((fn (ir-function-ref fi)))
            (let b ((bi 0))
              (when (< bi (function-block-count fn))
                (promote-block! (function-block-ref fn bi))
                (b (+ bi 1)))))
          (f (+ fi 1))))
      ir)))
