(define-library (ccweave kernel null-check-elim)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . null-check-elim) (version . "0.0.0") (description . "Eliminates null checks proven redundant.")))
    (define (kernel-capabilities) '(opt.null-check-elim))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.null-check-elim) (error "null-check-elim: unsupported capability" capability))
      (unless (list? options) (error "null-check-elim: options must be an alist" options))
      ir)))
