(define-library (ccweave kernel null-check-elim)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . null-check-elim)
        (version . "0.1.0")
        (description . "Eliminates repeated null checks of the same SSA value.")))
    (define (kernel-capabilities) '(opt.null-check-elim))

    (define (member-string? value values)
      (and (pair? values)
           (or (string=? value (car values))
               (member-string? value (cdr values)))))

    (define (checked-register instruction)
      (and (eq? (instr-opcode instruction) 'null-check)
           (= (instr-operand-count instruction) 1)
           (let ((operand (instr-operand instruction 0)))
             (and (eq? (operand-kind operand) 'reg)
                  (operand-name operand)))))

    (define (simplify-block! block)
      (let loop ((index 0) (checked '()))
        (when (< index (block-instr-count block))
          (let* ((instruction (block-instr-ref block index))
                 (name (checked-register instruction)))
            (if (and name (member-string? name checked))
                (begin
                  (instr-delete! instruction)
                  (loop index checked))
                (loop (+ index 1)
                      (if name (cons name checked) checked)))))))

    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.null-check-elim)
        (error "null-check-elim: unsupported capability" capability))
      (unless (list? options)
        (error "null-check-elim: options must be an alist" options))
      (unless (and (glue-has? 'operand-kind)
                   (glue-has? 'operand-name))
        (error "null-check-elim: scalar inspection accessors are unavailable"))
      (let functions ((function-index 0))
        (when (< function-index (ir-function-count))
          (let ((function (ir-function-ref function-index)))
            (let blocks ((block-index 0))
              (when (< block-index (function-block-count function))
                (simplify-block! (function-block-ref function block-index))
                (blocks (+ block-index 1)))))
          (functions (+ function-index 1))))
      ir)))
