;;; CCWeave Kernel: lower object-model vtable operations.

(define-library (ccweave kernel oop-vtable-lower)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . oop-vtable-lower)
        (version . "1.0.0")
        (description . "Lowers object vtable construction and lookup to runtime operations.")))
    (define (kernel-capabilities) '(lower.oop-vtable))
    (define (mapped opcode)
      (cond ((eq? opcode 'vtable.make) 'runtime.vtable.make)
            ((eq? opcode 'vtable.lookup) 'runtime.vtable.lookup)
            ((eq? opcode 'vtable.dispatch) 'runtime.vtable.dispatch)
            (else #f)))
    (define (operands ins)
      (let loop ((i 0) (out '()))
        (if (>= i (instr-operand-count ins))
            (reverse out)
            (loop (+ i 1) (cons (instr-operand ins i) out)))))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'lower.oop-vtable)
        (error "oop-vtable-lower: unsupported capability" capability))
      (unless (list? options)
        (error "oop-vtable-lower: options must be an alist" options))
      (unless (and (glue-has? 'instr-dest)
                   (glue-has? 'instr-set-dest!))
        (error "oop-vtable-lower: destination accessors are unavailable"))
      (let f ((fi 0))
        (when (< fi (ir-function-count))
          (let ((fn (ir-function-ref fi)))
            (let b ((bi 0))
              (when (< bi (function-block-count fn))
                (let ((block (function-block-ref fn bi)))
                  (let i ((ii 0))
                    (when (< ii (block-instr-count block))
                      (let* ((old (block-instr-ref block ii))
                             (new-op (mapped (instr-opcode old))))
                        (when new-op
                          (let ((new (apply instr-build
                                            (cons new-op (operands old)))))
                            (when (string? (instr-dest old))
                              (instr-set-dest! new (instr-dest old)))
                            (instr-replace! old new))))
                      (i (+ ii 1)))))
                  (b (+ bi 1)))))
          (f (+ fi 1))))
      ir)))
