;;; CCWeave Kernel: turn a virtual call into a direct call when its target is known.

(define-library (ccweave kernel oop-devirtualize)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . oop-devirtualize)
        (version . "1.0.0")
        (description . "Devirtualizes calls carrying an explicit function target.")))
    (define (kernel-capabilities) '(opt.oop-devirtualization))
    (define (operands ins)
      (let loop ((i 0) (out '()))
        (if (>= i (instr-operand-count ins))
            (reverse out)
            (loop (+ i 1) (cons (instr-operand ins i) out)))))
    (define (direct-target? ins)
      (and (eq? (instr-opcode ins) 'call.virtual)
           (> (instr-operand-count ins) 0)
           (let ((target (instr-operand ins (- (instr-operand-count ins) 1))))
             (eq? (operand-kind target) 'func))))
    (define (rewrite-block! block)
      (let loop ((i 0))
        (when (< i (block-instr-count block))
          (let ((old (block-instr-ref block i)))
            (when (direct-target? old)
              (let ((new (apply instr-build (cons 'call (operands old)))))
                (when (string? (instr-dest old))
                  (instr-set-dest! new (instr-dest old)))
                (instr-replace! old new)))
            (loop (+ i 1))))))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.oop-devirtualization)
        (error "oop-devirtualize: unsupported capability" capability))
      (unless (list? options)
        (error "oop-devirtualize: options must be an alist" options))
      (unless (and (glue-has? 'operand-kind)
                   (glue-has? 'instr-dest)
                   (glue-has? 'instr-set-dest!))
        (error "oop-devirtualize: required accessors are unavailable"))
      (let f ((fi 0))
        (when (< fi (ir-function-count))
          (let ((fn (ir-function-ref fi)))
            (let b ((bi 0))
              (when (< bi (function-block-count fn))
                (rewrite-block! (function-block-ref fn bi))
                (b (+ bi 1)))))
          (f (+ fi 1))))
      ir)))
