;;; CCWeave Kernel: record redundant object null checks.

(define-library (ccweave kernel oop-null-check)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . oop-null-check)
        (version . "1.0.0")
        (description . "Records object null checks that are immediately repeated.")))
    (define (kernel-capabilities) '(opt.oop-null-check-elimination))
    (define (same-check? a b)
      (and (eq? (instr-opcode a) 'null-check)
           (eq? (instr-opcode b) 'null-check)
           (= (instr-operand-count a) 1)
           (= (instr-operand-count b) 1)
           (eqv? (instr-operand a 0) (instr-operand b 0))))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.oop-null-check-elimination)
        (error "oop-null-check: unsupported capability" capability))
      (unless (list? options)
        (error "oop-null-check: options must be an alist" options))
      (unless (glue-has? 'analysis-put!)
        (error "oop-null-check: analysis accessor is unavailable"))
      (let f ((fi 0))
        (when (< fi (ir-function-count))
          (let ((fn (ir-function-ref fi)))
            (let b ((bi 0))
              (when (< bi (function-block-count fn))
                (let ((block (function-block-ref fn bi)))
                  (let i ((ii 1))
                    (when (< ii (block-instr-count block))
                      (when (same-check? (block-instr-ref block (- ii 1))
                                         (block-instr-ref block ii))
                        (analysis-put! 'opt.oop-null-check-elimination
                                       (block-instr-ref block ii)
                                       'redundant? #t))
                      (i (+ ii 1)))))
                (b (+ bi 1)))))
          (f (+ fi 1))))
      ir)))
