;;; kernels/overflow-lower.scm
;;; CCWeave Kernel: checked-arithmetic lowering.

(define-library (ccweave kernel overflow-lower)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . overflow-lower)
        (version . "0.1.0")
        (description . "Lowers checked integer arithmetic to explicit with-overflow operations.")))
    (define (kernel-capabilities) '(lower.overflow))

    (define (lowered-opcode opcode)
      (cond ((eq? opcode 'iadd.checked) 'iadd.with-overflow)
            ((eq? opcode 'isub.checked) 'isub.with-overflow)
            ((eq? opcode 'imul.checked) 'imul.with-overflow)
            (else #f)))

    (define (lower-block! block)
      (let loop ((index 0))
        (when (< index (block-instr-count block))
          (let* ((instruction (block-instr-ref block index))
                 (opcode (lowered-opcode (instr-opcode instruction))))
            (when (and opcode (= (instr-operand-count instruction) 2))
              (let ((replacement
                      (instr-build opcode
                                   (instr-operand instruction 0)
                                   (instr-operand instruction 1)))
                    (destination (instr-dest instruction)))
                (when (string? destination)
                  (instr-set-dest! replacement destination))
                (instr-replace! instruction replacement)))
            (loop (+ index 1))))))

    (define (kernel-apply capability ir options)
      (unless (eq? capability 'lower.overflow)
        (error "overflow-lower: unsupported capability" capability))
      (unless (list? options)
        (error "overflow-lower: options must be an alist" options))
      (unless (and (glue-has? 'instr-dest)
                   (glue-has? 'instr-set-dest!))
        (error "overflow-lower: scalar mutation accessors are unavailable"))
      (let functions ((function-index 0))
        (when (< function-index (ir-function-count))
          (let ((function (ir-function-ref function-index)))
            (let blocks ((block-index 0))
              (when (< block-index (function-block-count function))
                (lower-block! (function-block-ref function block-index))
                (blocks (+ block-index 1)))))
          (functions (+ function-index 1))))
      ir)))
