(define-library (ccweave kernel pattern-match-lower)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . pattern-match-lower) (version . "0.0.0") (description . "Lowers pattern matching into explicit tests and branches.")))
    (define (kernel-capabilities) '(lower.pattern-match))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'lower.pattern-match) (error "pattern-match-lower: unsupported capability" capability))
      (unless (list? options) (error "pattern-match-lower: options must be an alist" options))
      ir)))
