;;; kernels/peephole.scm
;;; CCWeave Kernel: target-parameterized peephole optimization.

(define-library (ccweave kernel peephole)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . peephole)
        (version . "0.1.0")
        (description . "Simplifies scalar integer identity operations.")))
    (define (kernel-capabilities) '(codegen.peephole))

    (define (integer=? operand value)
      (and (eq? (operand-kind operand) 'const-int)
           (= (const-int-value operand) value)))

    (define (identity-value instruction)
      (and (= (instr-operand-count instruction) 2)
           (let ((left (instr-operand instruction 0))
                 (right (instr-operand instruction 1))
                 (opcode (instr-opcode instruction)))
             (cond
               ((and (eq? opcode 'iadd) (integer=? left 0)) right)
               ((and (eq? opcode 'iadd) (integer=? right 0)) left)
               ((and (eq? opcode 'isub) (integer=? right 0)) left)
               ((and (eq? opcode 'imul) (integer=? left 1)) right)
               ((and (eq? opcode 'imul) (integer=? right 1)) left)
               ((and (eq? opcode 'ixor) (integer=? right 0)) left)
               (else #f)))))

    (define (self-copy? instruction)
      (and (eq? (instr-opcode instruction) 'imov)
           (= (instr-operand-count instruction) 1)
           (string? (instr-dest instruction))
           (let ((source (instr-operand instruction 0)))
             (and (eq? (operand-kind source) 'reg)
                  (string=? (instr-dest instruction)
                            (operand-name source))))))

    (define (simplify-block! block)
      (let loop ((index 0))
        (when (< index (block-instr-count block))
          (let* ((instruction (block-instr-ref block index))
                 (identity (identity-value instruction)))
            (cond
              ((self-copy? instruction)
               (instr-delete! instruction)
               (loop index))
              (identity
               (let ((replacement (instr-build 'imov identity))
                     (destination (instr-dest instruction)))
                 (when (string? destination)
                   (instr-set-dest! replacement destination))
                 (instr-replace! instruction replacement))
               (loop (+ index 1)))
              (else (loop (+ index 1))))))))

    (define (kernel-apply capability ir options)
      (unless (eq? capability 'codegen.peephole)
        (error "peephole: unsupported capability" capability))
      (unless (list? options)
        (error "peephole: options must be an alist" options))
      (unless (and (glue-has? 'operand-kind)
                   (glue-has? 'instr-dest)
                   (glue-has? 'instr-set-dest!))
        (error "peephole: scalar mutation accessors are unavailable"))
      (let functions ((function-index 0))
        (when (< function-index (ir-function-count))
          (let ((function (ir-function-ref function-index)))
            (let blocks ((block-index 0))
              (when (< block-index (function-block-count function))
                (simplify-block! (function-block-ref function block-index))
                (blocks (+ block-index 1)))))
          (functions (+ function-index 1))))
      ir)))
