(define-library (ccweave kernel phi-simplify)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . phi-simplify) (version . "0.0.0") (description . "Simplifies redundant SSA phi nodes.")))
    (define (kernel-capabilities) '(opt.phi-simplify))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.phi-simplify) (error "phi-simplify: unsupported capability" capability))
      (unless (list? options) (error "phi-simplify: options must be an alist" options))
      ir)))
