(define-library (ccweave kernel phi-simplify)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . phi-simplify)
        (version . "0.1.0")
        (description . "Replaces phi nodes whose incoming values are identical.")))
    (define (kernel-capabilities) '(opt.phi-simplify))

    (define (same-value? left right)
      (let ((left-kind (operand-kind left))
            (right-kind (operand-kind right)))
        (and (eq? left-kind right-kind)
             (cond
               ((eq? left-kind 'reg)
                (string=? (operand-name left) (operand-name right)))
               ((eq? left-kind 'const-int)
                (= (const-int-value left) (const-int-value right)))
               (else #f)))))

    (define (redundant-value instruction)
      (and (eq? (instr-opcode instruction) 'phi)
           (> (instr-operand-count instruction) 0)
           (let ((first (instr-operand instruction 0)))
             (let loop ((index 1))
               (cond
                 ((>= index (instr-operand-count instruction)) first)
                 ((same-value? first (instr-operand instruction index))
                  (loop (+ index 1)))
                 (else #f))))))

    (define (simplify-block! block)
      (let loop ((index 0))
        (when (< index (block-instr-count block))
          (let* ((instruction (block-instr-ref block index))
                 (value (redundant-value instruction)))
            (when value
              (let ((replacement (instr-build 'imov value))
                    (destination (instr-dest instruction)))
                (when (string? destination)
                  (instr-set-dest! replacement destination))
                (instr-replace! instruction replacement)))
            (loop (+ index 1))))))

    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.phi-simplify)
        (error "phi-simplify: unsupported capability" capability))
      (unless (list? options)
        (error "phi-simplify: options must be an alist" options))
      (unless (and (glue-has? 'operand-kind)
                   (glue-has? 'operand-name)
                   (glue-has? 'instr-dest)
                   (glue-has? 'instr-set-dest!))
        (error "phi-simplify: scalar inspection accessors are unavailable"))
      (let functions ((function-index 0))
        (when (< function-index (ir-function-count))
          (let ((function (ir-function-ref function-index)))
            (let blocks ((block-index 0))
              (when (< block-index (function-block-count function))
                (simplify-block! (function-block-ref function block-index))
                (blocks (+ block-index 1)))))
          (functions (+ function-index 1))))
      ir)))
