(define-library (ccweave kernel profile-report)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . profile-report) (version . "0.0.0") (description . "Reports the active IR profile and module shape.")))
    (define (kernel-capabilities) '(analysis.profile-report))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'analysis.profile-report) (error "profile-report: unsupported capability" capability))
      (unless (list? options) (error "profile-report: options must be an alist" options))
      ir)))
