(define-library (ccweave kernel profile-report)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . profile-report) (version . "0.1.0") (description . "Publishes the active IR profile for every function.")))
    (define (kernel-capabilities) '(analysis.profile-report))
    (define (kernel-apply cap ir options)
      (unless (eq? cap 'analysis.profile-report) (error "profile-report: unsupported capability" cap))
      (let loop ((i 0)) (when (< i (ir-function-count))
        (analysis-put! 'analysis.profile-report (ir-function-ref i) 'profile (ir-profile))
        (loop (+ i 1))))
      ir)))
