(define-library (ccweave kernel purity)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . purity) (version . "0.0.0") (description . "Classifies operations by observable side effects.")))
    (define (kernel-capabilities) '(analysis.purity))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'analysis.purity) (error "purity: unsupported capability" capability))
      (unless (list? options) (error "purity: options must be an alist" options))
      ir)))
