(define-library (ccweave kernel reaching-defs)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . reaching-defs) (version . "0.0.0") (description . "Computes reaching definitions for program points.")))
    (define (kernel-capabilities) '(analysis.reaching-definitions))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'analysis.reaching-definitions) (error "reaching-defs: unsupported capability" capability))
      (unless (list? options) (error "reaching-defs: options must be an alist" options))
      ir)))
