(define-library (ccweave kernel reaching-defs)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . reaching-defs) (version . "0.1.0") (description . "Publishes definitions that reach the end of their block.")))
    (define (kernel-capabilities) '(analysis.reaching-definitions))
    (define (redefined-after? name block start)
      (let loop ((i start)) (and (< i (block-instr-count block))
        (let ((dest (instr-dest (block-instr-ref block i))))
          (or (and dest (string=? dest name)) (loop (+ i 1)))))))
    (define (kernel-apply cap ir options)
      (unless (eq? cap 'analysis.reaching-definitions) (error "reaching-defs: unsupported capability" cap))
      (let f ((fi 0)) (when (< fi (ir-function-count))
        (let b ((bi 0) (fn (ir-function-ref fi))) (when (< bi (function-block-count fn))
          (let i ((ii 0) (blk (function-block-ref fn bi))) (when (< ii (block-instr-count blk))
            (let ((ins (block-instr-ref blk ii)) (dest (instr-dest (block-instr-ref blk ii))))
              (when dest (analysis-put! 'analysis.reaching-definitions ins 'reaches-block-end?
                                         (not (redefined-after? dest blk (+ ii 1))))))
            (i (+ ii 1) blk)))
          (b (+ bi 1) fn)))
        (f (+ fi 1))))
      ir)))
