(define-library (ccweave kernel regalloc-graph-color)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . regalloc-graph-color) (version . "0.0.0") (description . "Assigns registers using graph coloring.")))
    (define (kernel-capabilities) '(codegen.regalloc-graph))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'codegen.regalloc-graph) (error "regalloc-graph-color: unsupported capability" capability))
      (unless (list? options) (error "regalloc-graph-color: options must be an alist" options))
      ir)))
