(define-library (ccweave kernel regalloc-linear-scan)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . regalloc-linear-scan) (version . "0.0.0") (description . "Assigns registers with a linear-scan allocator.")))
    (define (kernel-capabilities) '(codegen.regalloc-linear))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'codegen.regalloc-linear) (error "regalloc-linear-scan: unsupported capability" capability))
      (unless (list? options) (error "regalloc-linear-scan: options must be an alist" options))
      ir)))
