(define-library (ccweave kernel regalloc-coalesce)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . regalloc-coalesce)
        (version . "0.1.0")
        (description . "Coalesces local register copies until redefinition.")))
    (define (kernel-capabilities) '(codegen.regalloc-coalesce))

    (define (replace-uses! block start destination source)
      (let instructions ((index start))
        (when (< index (block-instr-count block))
          (let ((instruction (block-instr-ref block index)))
            (unless (and (string? (instr-dest instruction))
                         (string=? (instr-dest instruction) destination))
              (let operands ((operand-index 0))
                (when (< operand-index (instr-operand-count instruction))
                  (let ((operand (instr-operand instruction operand-index)))
                    (when (and (eq? (operand-kind operand) 'reg)
                               (string=? (operand-name operand) destination))
                      (instr-set-operand! instruction operand-index
                                          (operand-reg-build source)))
                    (operands (+ operand-index 1)))))
              (instructions (+ index 1)))))))

    (define (coalesce-block! block)
      (let loop ((index 0))
        (when (< index (block-instr-count block))
          (let* ((instruction (block-instr-ref block index))
                 (destination (instr-dest instruction)))
            (if (and (string? destination)
                     (eq? (instr-opcode instruction) 'imov)
                     (= (instr-operand-count instruction) 1)
                     (eq? (operand-kind (instr-operand instruction 0)) 'reg))
                (let ((source (operand-name (instr-operand instruction 0))))
                  (replace-uses! block (+ index 1) destination source)
                  (instr-delete! instruction)
                  (loop index))
                (loop (+ index 1)))))))

    (define (kernel-apply capability ir options)
      (unless (eq? capability 'codegen.regalloc-coalesce)
        (error "regalloc-coalesce: unsupported capability" capability))
      (unless (list? options)
        (error "regalloc-coalesce: options must be an alist" options))
      (unless (and (glue-has? 'instr-dest)
                   (glue-has? 'operand-kind)
                   (glue-has? 'operand-name)
                   (glue-has? 'instr-set-operand!)
                   (glue-has? 'operand-reg-build))
        (error "regalloc-coalesce: scalar mutation accessors are unavailable"))
      (let functions ((function-index 0))
        (when (< function-index (ir-function-count))
          (let ((function (ir-function-ref function-index)))
            (let blocks ((block-index 0))
              (when (< block-index (function-block-count function))
                (coalesce-block! (function-block-ref function block-index))
                (blocks (+ block-index 1)))))
          (functions (+ function-index 1))))
      ir)))
