(define-library (ccweave kernel regalloc-linear-scan)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . regalloc-linear-scan)
        (version . "0.1.0")
        (description . "Publishes deterministic linear positions and virtual register slots.")))
    (define (kernel-capabilities) '(codegen.regalloc-linear))

    (define (scan-function! function)
      (let blocks ((block-index 0) (position 0) (slot 0))
        (if (>= block-index (function-block-count function))
            slot
            (let ((block (function-block-ref function block-index)))
              (let instructions ((instruction-index 0)
                                 (next-position position)
                                 (next-slot slot))
                (if (>= instruction-index (block-instr-count block))
                    (blocks (+ block-index 1) next-position next-slot)
                    (let ((instruction
                            (block-instr-ref block instruction-index)))
                      (analysis-put! 'codegen.regalloc-linear instruction
                                     'linear-position next-position)
                      (if (string? (instr-dest instruction))
                          (begin
                            (analysis-put! 'codegen.regalloc-linear instruction
                                           'virtual-register next-slot)
                            (instructions (+ instruction-index 1)
                                          (+ next-position 1)
                                          (+ next-slot 1)))
                          (instructions (+ instruction-index 1)
                                        (+ next-position 1)
                                        next-slot)))))))))

    (define (kernel-apply capability ir options)
      (unless (eq? capability 'codegen.regalloc-linear)
        (error "regalloc-linear-scan: unsupported capability" capability))
      (unless (list? options)
        (error "regalloc-linear-scan: options must be an alist" options))
      (unless (and (glue-has? 'analysis-put!)
                   (glue-has? 'instr-dest))
        (error "regalloc-linear-scan: analysis accessors are unavailable"))
      (let functions ((function-index 0))
        (when (< function-index (ir-function-count))
          (scan-function! (ir-function-ref function-index))
          (functions (+ function-index 1))))
      ir)))
