(define-library (ccweave kernel regalloc-coalesce)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . regalloc-coalesce) (version . "0.0.0") (description . "Coalesces compatible register-allocation moves.")))
    (define (kernel-capabilities) '(codegen.regalloc-coalesce))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'codegen.regalloc-coalesce) (error "regalloc-coalesce: unsupported capability" capability))
      (unless (list? options) (error "regalloc-coalesce: options must be an alist" options))
      ir)))
