;;; kernels/riscv64-codegen.scm
;;; CCWeave Kernel: RV64GC instruction selection.

(define-library (ccweave kernel riscv64-codegen)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . riscv64-codegen) (version . "0.2.0")
        (description . "Selects a scalar RV64GC instruction subset covering arithmetic, compares, memory, and control flow.")))
    (define (kernel-capabilities) '(codegen.riscv64))

    (define op-table
      '((imov       . rv64gc.mv)
        (iadd       . rv64gc.add)
        (isub       . rv64gc.sub)
        (imul       . rv64gc.mul)
        (idiv       . rv64gc.div)
        (irem       . rv64gc.rem)
        (iand       . rv64gc.and)
        (ior        . rv64gc.or)
        (ixor       . rv64gc.xor)
        (shl        . rv64gc.sll)
        (lshr       . rv64gc.srl)
        (ashr       . rv64gc.sra)
        (ineg       . rv64gc.neg)
        (inot       . rv64gc.not)
        (icmp.eq    . rv64gc.seq)
        (icmp.ne    . rv64gc.sne)
        (icmp.lt    . rv64gc.slt)
        (icmp.le    . rv64gc.sle)
        (icmp.gt    . rv64gc.sgt)
        (icmp.ge    . rv64gc.sge)
        (load       . rv64gc.ld)
        (store      . rv64gc.sd)
        (jmp        . rv64gc.j)
        (br         . rv64gc.beq)
        (ret        . rv64gc.ret)
        (call       . rv64gc.call)
        (syscall    . rv64gc.ecall)
        (call.dynamic . rv64gc.jalr)
        (call.virtual . rv64gc.jalr.virtual)
        (phi        . rv64gc.phi)))

    (define (mapped op)
      (let ((entry (assq op op-table)))
        (and entry (cdr entry))))

    (define (ops ins)
      (let loop ((i 0) (xs '())) (if (>= i (instr-operand-count ins)) (reverse xs)
        (loop (+ i 1) (cons (instr-operand ins i) xs)))))

    (define (select! b)
      (let loop ((i 0)) (when (< i (block-instr-count b))
        (let* ((old (block-instr-ref b i)) (op (mapped (instr-opcode old))))
          (when op (let ((new (apply instr-build (cons op (ops old)))) (d (instr-dest old)))
            (when (string? d) (instr-set-dest! new d)) (instr-replace! old new)))
          (loop (+ i 1))))))

    (define (kernel-apply capability ir options)
      (unless (eq? capability 'codegen.riscv64)
        (error "riscv64-codegen: unsupported capability" capability))
      (unless (list? options)
        (error "riscv64-codegen: options must be an alist" options))
      (unless (glue-has? 'instr-set-dest!) (error "riscv64-codegen: scalar mutation accessors are unavailable"))
      (let f ((fi 0)) (when (< fi (ir-function-count))
        (let ((fn (ir-function-ref fi))) (let b ((bi 0)) (when (< bi (function-block-count fn))
          (select! (function-block-ref fn bi)) (b (+ bi 1))))) (f (+ fi 1))))
      ir)))
