;;; kernels/riscv64-codegen.scm
;;; CCWeave Kernel: RV64GC instruction selection.

(define-library (ccweave kernel riscv64-codegen)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . riscv64-codegen) (version . "0.1.0")
        (description . "Selects a scalar RV64GC instruction subset.")))
    (define (kernel-capabilities) '(codegen.riscv64))
    (define (mapped op)
      (cond ((eq? op 'iadd) 'rv64gc.add) ((eq? op 'isub) 'rv64gc.sub)
            ((eq? op 'imul) 'rv64gc.mul) ((eq? op 'load) 'rv64gc.ld)
            ((eq? op 'store) 'rv64gc.sd) (else #f)))
    (define (ops ins)
      (let loop ((i 0) (xs '())) (if (>= i (instr-operand-count ins)) (reverse xs)
        (loop (+ i 1) (cons (instr-operand ins i) xs)))))
    (define (select! b)
      (let loop ((i 0)) (when (< i (block-instr-count b))
        (let* ((old (block-instr-ref b i)) (op (mapped (instr-opcode old))))
          (when op (let ((new (apply instr-build (cons op (ops old)))) (d (instr-dest old)))
            (when (string? d) (instr-set-dest! new d)) (instr-replace! old new)))
          (loop (+ i 1))))))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'codegen.riscv64)
        (error "riscv64-codegen: unsupported capability" capability))
      (unless (list? options)
        (error "riscv64-codegen: options must be an alist" options))
      (unless (glue-has? 'instr-set-dest!) (error "riscv64-codegen: scalar mutation accessors are unavailable"))
      (let f ((fi 0)) (when (< fi (ir-function-count))
        (let ((fn (ir-function-ref fi))) (let b ((bi 0)) (when (< bi (function-block-count fn))
          (select! (function-block-ref fn bi)) (b (+ bi 1))))) (f (+ fi 1))))
      ir)))
