;;; kernels/safepoint-insert.scm
;;; CCWeave Kernel: VM safepoint insertion.

(define-library (ccweave kernel safepoint-insert)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . safepoint-insert) (version . "0.1.0")
        (description . "Inserts idempotent On1x safepoint polls before calls.")))
    (define (kernel-capabilities) '(vm.safepoint-insertion))
    (define (call? op) (or (eq? op 'call) (eq? op 'call.dynamic)))
    (define (instrument-block! block)
      (let loop ((i 0))
        (when (< i (block-instr-count block))
          (let ((ins (block-instr-ref block i)))
            (if (and (call? (instr-opcode ins))
                     (or (= i 0)
                         (not (eq? (instr-opcode (block-instr-ref block (- i 1)))
                                   'safepoint))))
                (begin (instr-insert-before! ins (instr-build 'safepoint))
                       (loop (+ i 2)))
                (loop (+ i 1)))))))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'vm.safepoint-insertion)
        (error "safepoint-insert: unsupported capability" capability))
      (unless (list? options)
        (error "safepoint-insert: options must be an alist" options))
      (unless (eq? (ir-profile) 'on1x)
        (error "safepoint-insert: capability requires the on1x profile"))
      (let f ((fi 0)) (when (< fi (ir-function-count))
        (let ((fn (ir-function-ref fi))) (let b ((bi 0))
          (when (< bi (function-block-count fn))
            (instrument-block! (function-block-ref fn bi)) (b (+ bi 1)))))
        (f (+ fi 1))))
      ir)))
