(define-library (ccweave kernel sccp)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . sccp) (version . "0.1.0") (description . "Folds constant integer add, subtract, and multiply instructions.")))
    (define (kernel-capabilities) '(opt.sccp))
    (define (fold op a b) (cond ((eq? op 'iadd) (+ a b)) ((eq? op 'isub) (- a b)) (else (* a b))))
    (define (kernel-apply cap ir options)
      (unless (eq? cap 'opt.sccp) (error "sccp: unsupported capability" cap))
      (let f ((fi 0)) (when (< fi (ir-function-count))
        (let b ((bi 0) (fn (ir-function-ref fi))) (when (< bi (function-block-count fn))
          (let i ((ii 0) (blk (function-block-ref fn bi))) (when (< ii (block-instr-count blk))
            (let ((ins (block-instr-ref blk ii)))
              (when (and (memq (instr-opcode ins) '(iadd isub imul)) (= (instr-operand-count ins) 2))
                (let ((a (instr-operand ins 0)) (b (instr-operand ins 1)))
                  (when (and (operand-const? a) (operand-const? b))
                    (let ((new (instr-build 'imov (const-int-build (fold (instr-opcode ins) (const-int-value a) (const-int-value b)))))
                          (dest (instr-dest ins)))
                      (when dest (instr-set-dest! new dest))
                      (instr-replace! ins new)))))
            (i (+ ii 1) blk)))
          (b (+ bi 1) fn)))
        (f (+ fi 1))))
      ir))))
