(define-library (ccweave kernel sched-critical-path)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . sched-critical-path) (version . "0.0.0") (description . "Schedules machine instructions along critical paths.")))
    (define (kernel-capabilities) '(codegen.sched-critical-path))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'codegen.sched-critical-path) (error "sched-critical-path: unsupported capability" capability))
      (unless (list? options) (error "sched-critical-path: options must be an alist" options))
      ir)))
