(define-library (ccweave kernel sched-critical-path)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . sched-critical-path)
        (version . "0.1.0")
        (description . "Publishes deterministic reverse-distance scheduling priorities.")))
    (define (kernel-capabilities) '(codegen.sched-critical-path))

    (define (prioritize-block! block)
      (let ((count (block-instr-count block)))
        (let loop ((index 0))
          (when (< index count)
            (analysis-put! 'codegen.sched-critical-path
                           (block-instr-ref block index)
                           'priority
                           (- count index))
            (loop (+ index 1))))))

    (define (kernel-apply capability ir options)
      (unless (eq? capability 'codegen.sched-critical-path)
        (error "sched-critical-path: unsupported capability" capability))
      (unless (list? options)
        (error "sched-critical-path: options must be an alist" options))
      (unless (glue-has? 'analysis-put!)
        (error "sched-critical-path: analysis accessors are unavailable"))
      (let functions ((function-index 0))
        (when (< function-index (ir-function-count))
          (let ((function (ir-function-ref function-index)))
            (let blocks ((block-index 0))
              (when (< block-index (function-block-count function))
                (prioritize-block! (function-block-ref function block-index))
                (blocks (+ block-index 1)))))
          (functions (+ function-index 1))))
      ir)))
