;;; kernels/slp-vectorize.scm
;;; CCWeave Kernel: superword-level parallelism vectorization.

(define-library (ccweave kernel slp-vectorize)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . slp-vectorize) (version . "0.1.0")
        (description . "Publishes adjacent isomorphic scalar pairs as SLP packs.")))
    (define (kernel-capabilities) '(opt.slp-vectorize))
    (define (packable? ins)
      (and (= (instr-operand-count ins) 2)
           (string? (instr-dest ins))
           (memq (instr-opcode ins) '(iadd isub imul iand ior ixor))))
    (define (analyze-block! block next)
      (let loop ((i 0) (pack next))
        (if (>= (+ i 1) (block-instr-count block)) pack
            (let ((a (block-instr-ref block i))
                  (b (block-instr-ref block (+ i 1))))
              (if (and (packable? a) (packable? b)
                       (eq? (instr-opcode a) (instr-opcode b)))
                  (begin
                    (analysis-put! 'opt.slp-vectorize a 'pack-id pack)
                    (analysis-put! 'opt.slp-vectorize b 'pack-id pack)
                    (loop (+ i 2) (+ pack 1)))
                  (loop (+ i 1) pack))))))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.slp-vectorize)
        (error "slp-vectorize: unsupported capability" capability))
      (unless (list? options)
        (error "slp-vectorize: options must be an alist" options))
      (unless (and (glue-has? 'analysis-put!) (glue-has? 'instr-dest))
        (error "slp-vectorize: analysis accessors are unavailable"))
      (let f ((fi 0) (pack 0))
        (when (< fi (ir-function-count))
          (let ((fn (ir-function-ref fi)))
            (let b ((bi 0) (next pack))
              (if (>= bi (function-block-count fn))
                  (f (+ fi 1) next)
                  (b (+ bi 1)
                     (analyze-block! (function-block-ref fn bi) next)))))))
      ir)))
