(define-library (ccweave kernel spill-slot-pack)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . spill-slot-pack) (version . "0.0.0") (description . "Packs stack spill slots to reduce frame size.")))
    (define (kernel-capabilities) '(codegen.spill-slot-pack))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'codegen.spill-slot-pack) (error "spill-slot-pack: unsupported capability" capability))
      (unless (list? options) (error "spill-slot-pack: options must be an alist" options))
      ir)))
