(define-library (ccweave kernel ssa-construct)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . ssa-construct) (version . "0.0.0") (description . "Constructs static single-assignment form.")))
    (define (kernel-capabilities) '(transform.ssa-construct))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'transform.ssa-construct) (error "ssa-construct: unsupported capability" capability))
      (unless (list? options) (error "ssa-construct: options must be an alist" options))
      ir)))
