(define-library (ccweave kernel ssa-destruct)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . ssa-destruct) (version . "0.0.0") (description . "Eliminates static single-assignment form.")))
    (define (kernel-capabilities) '(transform.ssa-destruct))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'transform.ssa-destruct) (error "ssa-destruct: unsupported capability" capability))
      (unless (list? options) (error "ssa-destruct: options must be an alist" options))
      ir)))
