(define-library (ccweave kernel ssa-construct)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . ssa-construct)
        (version . "0.1.0")
        (description . "Constructs local SSA names for repeated definitions within a block.")))
    (define (kernel-capabilities) '(transform.ssa-construct))

    (define (construct-block! block)
      (let ((current '()) (counts '()))
        (define (lookup table name)
          (let ((entry (assoc name table)))
            (and entry (cdr entry))))
        (define (remember-current! name value)
          (set! current (cons (cons name value) current)))
        (define (next-name! name)
          (let ((count (or (lookup counts name) 0)))
            (set! counts (cons (cons name (+ count 1)) counts))
            (if (= count 0)
                name
                (string-append
                  name ".ssa" (number->string count)))))
        (let instructions ((instruction-index 0))
          (when (< instruction-index (block-instr-count block))
            (let ((instruction
                    (block-instr-ref block instruction-index)))
              (let operands ((operand-index 0))
                (when (< operand-index (instr-operand-count instruction))
                  (let ((operand
                          (instr-operand instruction operand-index)))
                    (when (eq? (operand-kind operand) 'reg)
                      (let ((replacement
                              (lookup current (operand-name operand))))
                        (when replacement
                          (instr-set-operand!
                            instruction operand-index
                            (operand-reg-build replacement)))))
                    (operands (+ operand-index 1)))))
              (let ((destination (instr-dest instruction)))
                (when (string? destination)
                  (let ((renamed (next-name! destination)))
                    (unless (string=? renamed destination)
                      (instr-set-dest! instruction renamed))
                    (remember-current! destination renamed))))
              (instructions (+ instruction-index 1)))))))

    (define (kernel-apply capability ir options)
      (unless (eq? capability 'transform.ssa-construct)
        (error "ssa-construct: unsupported capability" capability))
      (unless (list? options)
        (error "ssa-construct: options must be an alist" options))
      (unless (and (glue-has? 'instr-dest)
                   (glue-has? 'instr-set-dest!)
                   (glue-has? 'operand-kind)
                   (glue-has? 'operand-name)
                   (glue-has? 'instr-set-operand!)
                   (glue-has? 'operand-reg-build))
        (error "ssa-construct: scalar mutation accessors are unavailable"))
      (let functions ((function-index 0))
        (when (< function-index (ir-function-count))
          (let ((function (ir-function-ref function-index)))
            (let blocks ((block-index 0))
              (when (< block-index (function-block-count function))
                (construct-block! (function-block-ref function block-index))
                (blocks (+ block-index 1)))))
          (functions (+ function-index 1))))
      ir)))
