(define-library (ccweave kernel ssa-destruct)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . ssa-destruct)
        (version . "0.1.0")
        (description . "Eliminates single-input phi nodes as copies.")))
    (define (kernel-capabilities) '(transform.ssa-destruct))

    (define (destruct-block! block)
      (let loop ((index 0))
        (when (< index (block-instr-count block))
          (let ((instruction (block-instr-ref block index)))
            (when (and (eq? (instr-opcode instruction) 'phi)
                       (= (instr-operand-count instruction) 1))
              (let ((replacement
                      (instr-build 'imov (instr-operand instruction 0)))
                    (destination (instr-dest instruction)))
                (when (string? destination)
                  (instr-set-dest! replacement destination))
                (instr-replace! instruction replacement)))
            (loop (+ index 1))))))

    (define (kernel-apply capability ir options)
      (unless (eq? capability 'transform.ssa-destruct)
        (error "ssa-destruct: unsupported capability" capability))
      (unless (list? options)
        (error "ssa-destruct: options must be an alist" options))
      (unless (and (glue-has? 'instr-dest)
                   (glue-has? 'instr-set-dest!))
        (error "ssa-destruct: scalar mutation accessors are unavailable"))
      (let functions ((function-index 0))
        (when (< function-index (ir-function-count))
          (let ((function (ir-function-ref function-index)))
            (let blocks ((block-index 0))
              (when (< block-index (function-block-count function))
                (destruct-block! (function-block-ref function block-index))
                (blocks (+ block-index 1)))))
          (functions (+ function-index 1))))
      ir)))
