;;; kernels/tailcall-mark.scm
;;; CCWeave Kernel: tail-call marking.

(define-library (ccweave kernel tailcall-mark)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . tailcall-mark)
        (version . "0.1.0")
        (description . "Publishes direct-return tail-position facts for calls.")))
    (define (kernel-capabilities) '(opt.tailcall))

    (define (mark-block! block)
      (let ((count (block-instr-count block)))
        (when (>= count 2)
          (let ((call (block-instr-ref block (- count 2)))
                (return (block-instr-ref block (- count 1))))
            (when (and (eq? (instr-opcode call) 'call)
                       (eq? (instr-opcode return) 'ret)
                       (= (instr-operand-count return) 1)
                       (string? (instr-dest call))
                       (let ((value (instr-operand return 0)))
                         (and (eq? (operand-kind value) 'reg)
                              (string=? (instr-dest call)
                                        (operand-name value)))))
              (analysis-put! 'opt.tailcall call 'tail-position? #t))))))

    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.tailcall)
        (error "tailcall-mark: unsupported capability" capability))
      (unless (list? options)
        (error "tailcall-mark: options must be an alist" options))
      (unless (and (glue-has? 'analysis-put!)
                   (glue-has? 'instr-dest)
                   (glue-has? 'operand-kind)
                   (glue-has? 'operand-name))
        (error "tailcall-mark: analysis accessors are unavailable"))
      (let functions ((function-index 0))
        (when (< function-index (ir-function-count))
          (let ((function (ir-function-ref function-index)))
            (let blocks ((block-index 0))
              (when (< block-index (function-block-count function))
                (mark-block! (function-block-ref function block-index))
                (blocks (+ block-index 1)))))
          (functions (+ function-index 1))))
      ir)))
