(define-library (ccweave kernel tail-call)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . tail-call)
        (version . "0.1.0")
        (description . "Marks calls returned directly by their containing block.")))
    (define (kernel-capabilities) '(opt.tailcall))

    (define (returned-call? call return)
      (and (eq? (instr-opcode call) 'call)
           (eq? (instr-opcode return) 'ret)
           (= (instr-operand-count return) 1)
           (let ((destination (instr-dest call))
                 (value (instr-operand return 0)))
             (and destination
                  (string? destination)
                  (eq? (operand-kind value) 'reg)
                  (string=? destination (operand-name value))))))

    (define (mark-block! block)
      (let ((count (block-instr-count block)))
        (when (>= count 2)
          (let ((call (block-instr-ref block (- count 2)))
                (return (block-instr-ref block (- count 1))))
            (when (returned-call? call return)
              (analysis-put! 'opt.tailcall call 'eligible? #t))))))

    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.tailcall)
        (error "tail-call: unsupported capability" capability))
      (unless (list? options)
        (error "tail-call: options must be an alist" options))
      (unless (and (glue-has? 'instr-dest)
                   (glue-has? 'operand-kind)
                   (glue-has? 'operand-name)
                   (glue-has? 'analysis-put!))
        (error "tail-call: analysis accessors are unavailable"))
      (let functions ((function-index 0))
        (when (< function-index (ir-function-count))
          (let ((function (ir-function-ref function-index)))
            (let blocks ((block-index 0))
              (when (< block-index (function-block-count function))
                (mark-block! (function-block-ref function block-index))
                (blocks (+ block-index 1)))))
          (functions (+ function-index 1))))
      ir)))
