(define-library (ccweave kernel tail-call)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . tail-call) (version . "0.0.0") (description . "Marks eligible calls for tail-call execution.")))
    (define (kernel-capabilities) '(opt.tailcall))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.tailcall) (error "tail-call: unsupported capability" capability))
      (unless (list? options) (error "tail-call: options must be an alist" options))
      ir)))
