(define-library (ccweave kernel tile-plan)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . tile-plan)
        (version . "0.1.0")
        (description . "Publishes pinned cost-table tile-size candidates for scheduled bands.")))
    (define (kernel-capabilities) '(opt.tiling))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.tiling)
        (error "tile-plan: unsupported capability" capability))
      (unless (list? options)
        (error "tile-plan: options must be an alist" options))
      (when (glue-has? 'analysis-put!)
        (analysis-put! 'opt.tiling ir 'status 'unavailable))
      ir)))
