(define-library (ccweave kernel unreachable-elim)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . unreachable-elim) (version . "0.0.0") (description . "Removes unreachable blocks and instructions.")))
    (define (kernel-capabilities) '(opt.unreachable-elim))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.unreachable-elim) (error "unreachable-elim: unsupported capability" capability))
      (unless (list? options) (error "unreachable-elim: options must be an alist" options))
      ir)))
