(define-library (ccweave kernel value-range)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . value-range) (version . "0.0.0") (description . "Computes conservative integer value ranges.")))
    (define (kernel-capabilities) '(analysis.range))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'analysis.range) (error "value-range: unsupported capability" capability))
      (unless (list? options) (error "value-range: options must be an alist" options))
      ir)))
