(define-library (ccweave kernel value-range)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . value-range) (version . "0.1.0") (description . "Publishes exact ranges for integer constants.")))
    (define (kernel-capabilities) '(analysis.range))

    (define (range-block! block)
      (let instructions ((instruction-index 0) (instruction-count (block-instr-count block)))
        (when (< instruction-index instruction-count)
          (let ((instruction (block-instr-ref block instruction-index)))
            (let operands ((operand-index 0) (operand-count (instr-operand-count instruction)))
              (when (< operand-index operand-count)
                (let ((operand (instr-operand instruction operand-index)))
                  (when (operand-const? operand)
                    (let ((value (const-int-value operand)))
                      (analysis-put! 'analysis.range operand 'min value)
                      (analysis-put! 'analysis.range operand 'max value)))
                  (operands (+ operand-index 1) operand-count))))
            (instructions (+ instruction-index 1) instruction-count)))))

    (define (kernel-apply capability ir options)
      (unless (eq? capability 'analysis.range) (error "value-range: unsupported capability" capability))
      (unless (glue-has? 'analysis-put!) (error "value-range: analysis facts are unavailable"))
      (let functions ((function-index 0) (function-count (ir-function-count)))
        (when (< function-index function-count)
          (let ((function (ir-function-ref function-index)))
            (let blocks ((block-index 0) (block-count (function-block-count function)))
              (when (< block-index block-count)
                (range-block! (function-block-ref function block-index))
                (blocks (+ block-index 1) block-count))))
          (functions (+ function-index 1) function-count)))
      ir)))
