(define-library (ccweave kernel varargs-lower)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info) '((name . varargs-lower) (version . "0.0.0") (description . "Lowers variadic argument access to explicit operations.")))
    (define (kernel-capabilities) '(lower.varargs))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'lower.varargs) (error "varargs-lower: unsupported capability" capability))
      (unless (list? options) (error "varargs-lower: options must be an alist" options))
      ir)))
