(define-library (ccweave kernel vec-reduce)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . vec-reduce) (version . "0.1.0")
        (description . "Marks ordered vector reductions and their scalar-tail policy.")))
    (define (kernel-capabilities) '(opt.vector-reduction))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'opt.vector-reduction)
        (error "vec-reduce: unsupported capability" capability))
      (unless (list? options) (error "vec-reduce: options must be an alist" options))
      (unless (glue-has? 'analysis-put!) (error "vec-reduce: analysis accessors unavailable"))
      (let f ((fi 0))
        (when (< fi (ir-function-count))
          (let ((fn (ir-function-ref fi)))
            (let b ((bi 0))
              (when (< bi (function-block-count fn))
                (let ((blk (function-block-ref fn bi)))
                  (let i ((ii 0))
                    (when (< ii (block-instr-count blk))
                      (let ((ins (block-instr-ref blk ii)))
                        (when (memq (instr-opcode ins)
                                    '(vadd.f32x4 vadd.f32x8 vmul.f32x4 vmul.f32x8))
                          (analysis-put! 'opt.vector-reduction ins 'ordered? #t)
                          (analysis-put! 'opt.vector-reduction ins 'tail-fold 'scalar)))
                      (i (+ ii 1)))))
                (b (+ bi 1)))))
          (f (+ fi 1))))
      ir)))
