(define-library (ccweave kernel vec-lower-simde)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . vec-lower-simde) (version . "0.1.0")
        (description . "Lowers width-explicit vector IR operations through the SIMDe Glue surface.")))
    (define (kernel-capabilities) '(lower.vector-simde))
    (define (lower-op op)
      (cond ((eq? op 'vadd.f32x4) 'ccw_simde_add_f32x4)
            ((eq? op 'vsub.f32x4) 'ccw_simde_sub_f32x4)
            ((eq? op 'vmul.f32x4) 'ccw_simde_mul_f32x4)
            ((eq? op 'vadd.i32x4) 'ccw_simde_add_i32x4)
            ((eq? op 'vsub.i32x4) 'ccw_simde_sub_i32x4)
            ((eq? op 'vmul.i32x4) 'ccw_simde_mul_i32x4)
            ((eq? op 'vadd.f32x8) 'ccw_simde_add_f32x8)
            ((eq? op 'vmul.f32x8) 'ccw_simde_mul_f32x8)
            (else #f)))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'lower.vector-simde)
        (error "vec-lower-simde: unsupported capability" capability))
      (unless (list? options) (error "vec-lower-simde: options must be an alist" options))
      (unless (and (glue-has? 'instr-build) (glue-has? 'instr-replace!)
                   (glue-has? 'instr-opcode))
        (error "vec-lower-simde: required accessors unavailable"))
      (let f ((fi 0))
        (when (< fi (ir-function-count))
          (let ((fn (ir-function-ref fi)))
            (let b ((bi 0))
              (when (< bi (function-block-count fn))
                (let ((blk (function-block-ref fn bi)))
                  (let i ((ii 0))
                    (when (< ii (block-instr-count blk))
                      (let* ((old (block-instr-ref blk ii)) (op (lower-op (instr-opcode old))))
                        (when op
                          (let ((new (apply instr-build (cons op (let ops ((j 0) (r '()))
                                                                  (if (>= j (instr-operand-count old)) (reverse r)
                                                                      (ops (+ j 1) (cons (instr-operand old j) r))))))))
                            (when (and (glue-has? 'instr-dest) (instr-dest old))
                              (instr-set-dest! new (instr-dest old)))
                            (instr-replace! old new)))
                        (i (+ ii 1)))))
                (b (+ bi 1)))))
          (f (+ fi 1))))
      ir))))
