(define-library (ccweave kernel vec-width)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . vec-width) (version . "0.1.0")
        (description . "Publishes deterministic target-keyed vector widths and lane counts.")))
    (define (kernel-capabilities) '(analysis.vector-width))
    (define (option-ref options key default)
      (let ((p (assoc key options))) (if p (cdr p) default)))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'analysis.vector-width)
        (error "vec-width: unsupported capability" capability))
      (unless (list? options) (error "vec-width: options must be an alist" options))
      (unless (glue-has? 'analysis-put!) (error "vec-width: analysis accessors unavailable"))
      (let* ((target (option-ref options 'target "x86-64"))
             (wide? (or (string=? target "x86-64-avx2")
                        (string=? target "aarch64-sve")))
             (f32 (if wide? 8 4))
             (f64 (if wide? 4 2))
             (i32 (if wide? 8 4)))
        (let f ((i 0))
          (when (< i (ir-function-count))
            (let ((fn (ir-function-ref i)))
              (analysis-put! 'analysis.vector-width fn 'target target)
              (analysis-put! 'analysis.vector-width fn 'width-bits (if wide? 256 128))
              (analysis-put! 'analysis.vector-width fn 'lanes-f32 f32)
              (analysis-put! 'analysis.vector-width fn 'lanes-f64 f64)
              (analysis-put! 'analysis.vector-width fn 'lanes-i32 i32))
            (f (+ i 1)))))
      ir)))
