(define-library (ccweave kernel vec-legality)
  (import (scheme base) (ccweave glue))
  (export kernel-info kernel-capabilities kernel-apply)
  (begin
    (define (kernel-info)
      '((name . vec-legality) (version . "0.1.0")
        (description . "Publishes conservative legality facts for self-evident single-block loops.")))
    (define (kernel-capabilities) '(analysis.vectorizable))
    (define (safe-op? op)
      (memq op '(iadd isub imul iand ior ixor fadd fsub fmul br jmp ret)))
    (define (kernel-apply capability ir options)
      (unless (eq? capability 'analysis.vectorizable)
        (error "vec-legality: unsupported capability" capability))
      (unless (list? options) (error "vec-legality: options must be an alist" options))
      (unless (and (glue-has? 'analysis-put!) (glue-has? 'block-succ-count)
                   (glue-has? 'block-succ-ref) (glue-has? 'instr-opcode))
        (error "vec-legality: required accessors unavailable"))
      (let f ((fi 0))
        (when (< fi (ir-function-count))
          (let ((fn (ir-function-ref fi)))
            (let b ((bi 0))
              (when (< bi (function-block-count fn))
                (let* ((blk (function-block-ref fn bi))
                       (self-loop (and (= (block-succ-count blk) 1)
                                       (eqv? (block-succ-ref blk 0) blk))))
                  (let scan ((ii 0) (ok self-loop))
                    (if (>= ii (block-instr-count blk))
                        (begin
                          (analysis-put! 'analysis.vectorizable blk 'legal? ok)
                          (analysis-put! 'analysis.vectorizable blk 'reason
                                         (if ok "unit-stride-single-block" "unsupported-op")))
                        (let ((op (instr-opcode (block-instr-ref blk ii))))
                          (scan (+ ii 1) (and ok (if (safe-op? op) #t #f)))))))
                (b (+ bi 1)))))
          (f (+ fi 1))))
      ir)))
