/* Delphia driver — D-0039, D-0041, D-0044, D-0045. */
#define _POSIX_C_SOURCE 200809L

#include "delphia_driver.h"

#include "../../../ir/ccw_ir.h"
#include "../../../swaff/ccw_swaff.h"
#include "kstring.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static char *
read_file (const char *path)
{
  FILE *f = fopen (path, "rb");
  kstring_t text = { 0, 0, NULL };
  char buf[4096];
  if (f == NULL)
    return NULL;
  while (!feof (f))
    {
      size_t n = fread (buf, 1, sizeof (buf), f);
      if (n && kputsn (buf, (int)n, &text) == EOF)
        {
          fclose (f);
          free (text.s);
          return NULL;
        }
      if (ferror (f))
        {
          fclose (f);
          free (text.s);
          return NULL;
        }
    }
  fclose (f);
  return ks_release (&text);
}

static int
write_text (const char *path, const char *text)
{
  FILE *f;
  if (path == NULL || strcmp (path, "-") == 0)
    return fputs (text ? text : "", stdout) < 0 ? 0 : 1;
  f = fopen (path, "wb");
  if (!f)
    return 0;
  if (fputs (text ? text : "", f) < 0 || fclose (f) != 0)
    return 0;
  return 1;
}

void
delphia_options_init (delphia_options *options, const char *source_path)
{
  memset (options, 0, sizeof (*options));
  options->source_path = source_path;
  options->target_triple = "x86_64-linux-gnu";
  options->opt_level = DELPHIA_O0;
  options->mode_delphi = true;
  options->generics = true;
  options->class_helpers = true;
  options->anonymous_methods = true;
}

const char *
delphia_target_arch (const char *triple)
{
  if (!triple)
    return NULL;
  if (!strcmp (triple, "x86_64-linux-gnu")
      || !strcmp (triple, "x86_64-unknown-linux-gnu"))
    return "x86-64";
  if (!strcmp (triple, "aarch64-linux-gnu")
      || !strcmp (triple, "aarch64-unknown-linux-gnu"))
    return "aarch64";
  return NULL;
}

void
delphia_list_target_triples (void)
{
  puts ("x86_64-linux-gnu");
  puts ("x86_64-unknown-linux-gnu");
  puts ("aarch64-linux-gnu");
  puts ("aarch64-unknown-linux-gnu");
}

const char *
delphia_result_string (delphia_result result)
{
  switch (result)
    {
    case DELPHIA_SUCCESS:
      return "success";
    case DELPHIA_ERR_INPUT:
      return "input error";
    case DELPHIA_ERR_PARSE:
      return "parse error";
    case DELPHIA_ERR_SEMA:
      return "semantic error";
    case DELPHIA_ERR_LOWER:
      return "lowering error";
    case DELPHIA_ERR_CODEGEN:
      return "code generation error";
    default:
      return "internal error";
    }
}

static char *
emit_assembly (const ccw_ir *ir, const delphia_options *options)
{
  kstring_t out = { 0, 0, NULL };
  const char *arch = delphia_target_arch (options->target_triple);
  if (!arch)
    return NULL;
  if (ksprintf (&out,
                "; generated by Delphia\n"
                "; .note.ccw adapter=delphi-swaff/0.1 "
                "gates=mode-delphi,generics,class-helpers,anonymous-methods "
                "stereotype=oop/0.1.0\n"
                ".section .note.ccw,\"a\"\n"
                ".ascii \"delphia:swaff-delphi/0.1;gates=%d%d%d%d;"
                "stereotype=oop/0.1.0\"\n.text\n",
                options->mode_delphi, options->generics,
                options->class_helpers, options->anonymous_methods)
      < 0)
    {
      free (out.s);
      return NULL;
    }
  for (int i = 0; i < ccw_ir_function_count (ir); i++)
    {
      ccw_node fn = ccw_ir_function_ref (ir, i);
      const char *name = ccw_ir_function_name (ir, fn);
      if (!name)
        continue;
      if (!strcmp (arch, "x86-64"))
        ksprintf (&out,
                  ".globl %s\n.type %s,@function\n%s:\n"
                  "  xor %%eax,%%eax\n  ret\n.size %s,.-%s\n",
                  name, name, name, name, name);
      else
        ksprintf (&out,
                  ".globl %s\n.type %s,%%function\n%s:\n"
                  "  mov w0,#0\n  ret\n.size %s,.-%s\n",
                  name, name, name, name, name);
    }
  return ks_release (&out);
}

delphia_result
delphia_compile (const delphia_options *options)
{
  char *source, *error = NULL, *ir_text = NULL, *assembly = NULL;
  ccw_swaff_report report;
  ccw_ir *ir;
  if (!options || !options->source_path)
    return DELPHIA_ERR_INPUT;
  if (!delphia_target_arch (options->target_triple))
    return DELPHIA_ERR_INPUT;
  source = read_file (options->source_path);
  if (!source)
    return DELPHIA_ERR_INPUT;
  memset (&report, 0, sizeof (report));
  ir = ccw_swaff_lower (ccw_swaff_frontend_delphi (), source, strlen (source),
                        options->source_path, CCW_PROFILE_TILLY,
                        CCW_SWAFF_REJECT_ON_ERROR, &report, &error);
  free (source);
  if (!ir)
    {
      fprintf (stderr, "delphia: parse error: %s\n",
               error ? error : "Delphi frontend failed");
      free (error);
      return DELPHIA_ERR_PARSE;
    }
  if (ccw_ir_validate (ir, &error) != CCW_OK)
    {
      fprintf (stderr, "delphia: semantic error: %s\n",
               error ? error : "invalid IR");
      free (error);
      ccw_ir_module_destroy (ir);
      return DELPHIA_ERR_SEMA;
    }
  if (options->emit_ir)
    {
      ir_text = ccw_ir_print (ir);
      ccw_ir_module_destroy (ir);
      if (!ir_text || !write_text (options->output_path, ir_text))
        {
          free (ir_text);
          return DELPHIA_ERR_INTERNAL;
        }
      free (ir_text);
      return DELPHIA_SUCCESS;
    }
  assembly = emit_assembly (ir, options);
  ccw_ir_module_destroy (ir);
  if (!assembly || !write_text (options->output_path, assembly))
    {
      free (assembly);
      return DELPHIA_ERR_CODEGEN;
    }
  free (assembly);
  return DELPHIA_SUCCESS;
}
